// Historical identities whose execution/load meaning is too broad for one frozen tuple.
export const AMBIGUOUS_EXECUTION_IDENTITIES = [
  "45-Degree Back Extension, Hamstring Bias",
  "Back Extension (45 Degree)",
  "Barbell Curl",
  "Belt Squat",
  "Dip (Chest Emphasis)",
  "Dip (Triceps Emphasis)",
  "Glute Bridge",
  "Hack Squat",
  "Leg Press Calf Raise",
  "Lying Triceps Extension (Skull Crusher)",
  "Nordic Hamstring Curl",
  "Pallof Press",
  "Preacher Curl",
  "Reverse Lunge",
  "Reverse Wrist Curl",
  "Romanian Deadlift",
  "Russian Twist",
  "Seated Calf Raise",
  "Single-Leg Hip Thrust",
  "Sissy Squat",
  "Spider Curl",
  "Standing Calf Raise",
  "Stiff-Legged Deadlift",
  "T-Bar Row",
  "Walking Lunge",
  "Wrist Curl",
] as const;

// Exact identities whose logging semantics cannot be represented by the current rep/load fields.
export const UNSUPPORTED_MEASUREMENT_IDENTITIES = [
  "Copenhagen Plank",
  "Dead Hang",
  "Dragon Flag",
  "Farmer's Walk",
  "Landmine Press",
  "Landmine Rotation",
  "Meadows Row",
  "Overhead Carry",
  "Plank",
  "RKC Plank",
  "Side Plank",
  "Sled Drag",
  "Sled Pull",
  "Sled Push",
  "Suitcase Carry",
] as const;
