import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { chromium, expect, type Page } from '@playwright/test';
import { verificationSource } from '../../scripts/trainer2/verification-source';
async function main() {
const [base, confirmation] = process.argv.slice(2);
assert(confirmation === '--confirm-synthetic-trial' && /^http:\/\/127\.0\.0\.1:\d+$/.test(base));
const ready = JSON.parse(readFileSync('artifacts/trainer2/training-ui-evidence/demo-ready.json','utf8')); assert.equal(new URL(ready.url).origin,base);
const dir='artifacts/trainer2/active-set-evidence/';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1360,height:1000}});
const page=await context.newPage(); const errors:string[]=[],passes:string[]=[];
context.on('page',p=>{p.on('dialog',d=>void d.accept());p.on('pageerror',e=>errors.push(e.message));});
page.on('dialog',d=>void d.accept());page.on('pageerror',e=>errors.push(e.message));
const get=async(id:string)=>{const r=await context.request.get(base+'/api/trainer2/executions/'+id);assert(r.ok());return r.json();};
const panel=(p=page)=>p.getByRole('region',{name:'Active set',exact:true});
const queue=(p=page)=>p.getByRole('region',{name:'Exercise queue'});
const chips=(p=page)=>queue(p).getByRole('button',{name:/, set \d+,/});
const select=async(i:number,p=page)=>{await chips(p).nth(i).click();};
const reps=(p=page)=>panel(p).getByLabel(/Actual reps/);
const save=async(p=page)=>{await panel(p).getByRole('button',{name:/^(Log set|Save correction)$/}).click();};
try {
 await page.goto(ready.url); await expect(page.getByRole('link',{name:'Continue workout'}).or(page.getByRole('button',{name:'Start workout',exact:true}))).toBeVisible(); const continuing=page.getByRole('link',{name:'Continue workout'}); if(await continuing.count()) {await continuing.click();} else {await expect(page.getByRole('button',{name:'Start workout',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Start workout',exact:true}).click();} await expect(page).toHaveURL(/executions\//);
 const url=page.url(), id=url.split('/').at(-1)!; const initial=await get(id);
 await expect(panel().getByRole('heading',{name:initial.initial.occurrence.positions[0].exercise.name})).toBeVisible();
 await expect(page.locator('[aria-label$="actual result"]')).toHaveCount(1);
 await expect(panel()).toContainText('Previous ·'); await expect(panel().getByText('History',{exact:true})).toBeVisible();
 await page.screenshot({path:dir+'after-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'after-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await reps().fill('8');await panel().getByLabel(/Actual load$/).fill('70');await panel().getByLabel(/load unit$/).selectOption('kg');await panel().getByRole('button',{name:'2 RIR',exact:true}).click();
 await panel().getByText('History',{exact:true}).click();await expect(reps()).toHaveValue('8');await panel().getByText('History',{exact:true}).click();
 await select(3);await reps().fill('11');await expect(page.getByRole('button',{name:'Finish workout',exact:true})).toBeDisabled();
 await select(0);await expect(reps()).toHaveValue('8');await page.reload();await expect(reps()).toHaveValue('8');
 await save();await expect(panel()).toContainText('Set 2 of');await expect(panel()).toContainText('1 of 13 sets recorded');
 await expect(panel().getByLabel(/load unit$/)).toHaveValue('kg');await reps().fill('9');await save();await expect(panel()).toContainText('Set 3 of');
 await reps().fill('7');await save();await expect(reps()).toHaveValue('11');
 passes.push('One editor; history toggle and out-of-order drafts; reload; successive confirmed saves advance across exercises and preserve existing draft');
 await panel().getByRole('button',{name:'Discard input',exact:true}).click();
 await select(0);await panel().getByRole('button',{name:'Edit result'}).click();await reps().fill('9');await panel().getByLabel(/correction reason/).fill('Synthetic correction');await save();await expect(chips().nth(0)).not.toHaveAttribute('aria-label',/retained/);
 await select(0);await panel().getByRole('button',{name:'Edit result'}).click();await panel().getByLabel(/correction reason/).fill('Clear erroneous test');await panel().getByRole('button',{name:'Clear erroneous result'}).click();await expect(panel()).toContainText('Saved v3: Cleared');await expect(panel()).toContainText('2 of 13 sets recorded');
 await panel().getByRole('button',{name:'Re-record result'}).click();await reps().fill('0');await panel().getByLabel(/Actual load$/).fill('0');await panel().getByLabel(/load unit$/).selectOption('kg');await panel().getByLabel(/correction reason/).fill('Rerecord zero');await save();await expect(panel()).toContainText('3 of 13 sets recorded');
 assert.equal((await get(id)).results.find((r:any)=>r.targetId===initial.initial.positions[0].targets[0].id).result.reps.value,0);
 passes.push('Correction, clear progress decrement, re-record under original identity, zero reps and zero load');
 await select(3);await reps().fill('6');
 let release!:()=>void;let reached!:()=>void;const held=new Promise<void>(r=>reached=r);const wait=new Promise<void>(r=>release=r);
 await page.route('**/api/trainer2/executions/results',async route=>{const response=await route.fetch();reached();await wait;await route.fulfill({response});},{times:1});
 await save();await held;await select(5);await reps().fill('12');release();await expect(panel()).toContainText('4 of 13 sets recorded');await expect(reps()).toHaveValue('12');
 passes.push('Late accepted response updates correct target without changing selection or input');
 await panel().getByRole('button',{name:'Discard input'}).click();await select(4);await reps().fill('8');
 let original='';await page.route('**/api/trainer2/executions/results',async route=>{original=route.request().postData()!;await route.fetch();await route.abort('failed');},{times:1});
 await save();await expect(panel().getByRole('button',{name:'Check again',exact:true})).toBeEnabled();
 await page.reload();await expect(panel().getByRole('button',{name:'Check again',exact:true})).toBeEnabled();
 const retry=page.waitForRequest(r=>r.url().endsWith('/executions/results')&&r.method()==='POST');await panel().getByRole('button',{name:'Check again',exact:true}).click();assert.equal((await retry).postData(),original);
 await expect(panel()).toContainText('5 of 13 sets recorded');assert.equal((await get(id)).history.filter((r:any)=>r.targetId===JSON.parse(original).target.targetId).length,1);
 passes.push('Lost committed response retained over reload; byte-exact retry creates no duplicate history');
 const tab=await context.newPage();await tab.goto(url);await select(0,tab);await panel(tab).getByRole('button',{name:'Edit result'}).click();await reps(tab).fill('5');await panel(tab).getByLabel(/correction reason/).fill('Stale input');
 await select(0);await panel().getByRole('button',{name:'Edit result'}).click();await panel().getByLabel(/correction reason/).fill('Same value newer version');await save();await expect(panel()).toContainText('5 of 13 sets recorded');
 await save(tab);await expect(panel(tab).getByRole('button',{name:'Review latest result'})).toBeVisible();await expect(reps(tab)).toHaveValue('5');
 await panel(tab).getByRole('button',{name:'Review latest result'}).click();await panel(tab).getByRole('button',{name:'Use this version for my correction'}).click();await save(tab);await expect(panel(tab)).toContainText('Set 3 of');await tab.close();
 passes.push('Two-tab equal-value newer version conflicts; explicit review/rebase/save retains input');
 await page.reload();await expect(page.getByRole('button',{name:'Finish workout',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Finish workout',exact:true}).click();await expect(page.getByRole('button',{name:'Finish with unrecorded sets'})).toBeEnabled();
 let finishBody='';await page.route('**/api/trainer2/executions/finish',async route=>{finishBody=route.request().postData()!;await route.fetch();await route.abort('failed');},{times:1});
 await page.getByRole('button',{name:'Finish with unrecorded sets'}).click();await expect(page.getByRole('button',{name:'Check finish again'})).toBeEnabled();assert.equal(page.url(),url);
 await page.getByRole('button',{name:'Check finish again'}).click();await expect(page).toHaveURL(ready.url);await expect(page.getByText('Workout finished.',{exact:false})).toBeVisible();assert(JSON.parse(finishBody).intent.acknowledgeUnrecorded);
 const finished=await get(id);assert.equal(finished.results.filter((r:any)=>r.result).length,5);assert.equal(finished.finish.unknownTargetIds.length,8);
 passes.push('Explicit partial finish preserves unrecorded work; no home navigation until exact retry and authoritative readback');
 await page.getByRole('button',{name:'Start workout',exact:true}).click();await expect(page).toHaveURL(/executions\//);const allId=page.url().split('/').at(-1)!;
 const all=await get(allId);const total=all.initial.positions.reduce((n:number,p:any)=>n+p.targets.length,0);
 for(let i=0;i<total;i++){await expect(reps()).toBeEnabled();await reps().fill('8');await save();await expect(panel()).toContainText(`${i+1} of ${total} sets recorded`);}
 await expect(panel().getByRole('heading',{name:'Ready to finish'})).toBeVisible();await expect(page.locator('[aria-label$="actual result"]')).toHaveCount(0);
 await page.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('button',{name:'Confirm finish'}).click();await expect(page).toHaveURL(ready.url);
 passes.push('Every remaining set logs through browser, reaches ready-to-finish without automatic completion, and confirmed finish returns home');
 assert.deepEqual(errors,[]);
 writeFileSync(dir+'browser.json',JSON.stringify({source:verificationSource(),browser:browser.version(),passes,errors,executionId:id,allId,initial,finished},null,2));console.log(passes);
} finally {await browser.close();}

}
void main().catch(e=>{console.error(e);process.exitCode=1;});
