import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {chromium,expect,type Page} from '@playwright/test';
import {verificationSource} from '../../scripts/trainer2/verification-source';
async function main(){
 const [container,confirmation]=process.argv.slice(2);assert(confirmation==='--confirm-synthetic-trial'&&/^trainer2-draft-[a-f0-9]+$/.test(container));
 const ready=JSON.parse(readFileSync('artifacts/trainer2/prefill-evidence/ready.json','utf8')),base=ready.base;assert(/^http:\/\/127\.0\.0\.1:\d+$/.test(base));
 const meta=JSON.parse(execFileSync('docker',['inspect',container],{encoding:'utf8'}))[0];assert(meta.NetworkSettings.Ports['5432/tcp'][0].HostIp==='127.0.0.1');const database=meta.Config.Env.find((x:string)=>x.startsWith('POSTGRES_DB=')).split('=')[1];assert(database.startsWith('trainer2_disposable_'));
 const sql=(q:string)=>execFileSync('docker',['exec',container,'psql','-U','postgres','-d',database,'-Atc',q],{encoding:'utf8'}).trim();
 const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1360,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors:string[]=[],commands:any[]=[],checks:string[]=[];
 context.on('page',p=>{p.on('dialog',d=>void d.accept());p.on('pageerror',e=>errors.push(e.message))});page.on('dialog',d=>void d.accept());page.on('pageerror',e=>errors.push(e.message));
 const panel=(p=page)=>p.getByRole('region',{name:'Active set',exact:true}),queue=(p=page)=>p.getByRole('region',{name:'Exercise queue'}),chips=(p=page)=>queue(p).getByRole('button',{name:/, set \d+,/});
 const select=async(i:number,p=page)=>{await chips(p).nth(i).click();await expect(chips(p).nth(i)).toHaveAttribute('aria-pressed','true')};
 const load=(p=page)=>panel(p).getByLabel(/Actual load$/),reps=(p=page)=>panel(p).getByLabel(/Actual reps/),rir=(p=page)=>panel(p).getByLabel(/Actual RIR/);
 const save=async(p=page)=>{const response=p.waitForResponse(r=>r.url().endsWith('/executions/results')&&r.request().method()==='POST');await panel(p).getByRole('button',{name:/^(Log set|Update set)$/}).click();const r=await response;commands.push(r.request().postDataJSON());assert.equal(r.status(),200,await r.text())};
 const get=async(path:string)=>{const r=await fetch(base+path);assert(r.ok);return r.json()};let id='';const read=()=>get('/api/trainer2/executions/'+id);const row=async(index:number)=>{const e=await read();const ids=e.initial.positions.flatMap((p:any)=>p.targets.map((t:any)=>t.id));return e.results.find((r:any)=>r.targetId===ids[index])};
 const source=verificationSource(),dir='artifacts/trainer2/prefill-evidence/';
 try{
 await page.goto(ready.url);await page.getByRole('button',{name:'Start workout',exact:true}).click();await expect(page).toHaveURL(/executions\//);id=page.url().split('/').at(-1)!;await expect(load()).toHaveValue('130');
 const initial=await read();assert.equal(initial.firstSetLoads.find((x:any)=>x.positionId===initial.initial.occurrence.positions[1].id).result.result.measurement.value,'62.5');
 await expect(panel()).toContainText('130 lb suggested from prescription');assert.equal(await panel().getByText(/Primary ·|Secondary ·/).count(),0);
 for(const label of ['Decrease load by 10 lb','Decrease load by 5 lb','Increase load by 5 lb','Increase load by 10 lb','4 RIR','5 RIR'])await expect(panel().getByRole('button',{name:label,exact:true})).toBeVisible();
 assert.equal(await queue().getByText('Sets',{exact:true}).count(),0);
 await select(3);await expect(load()).toHaveValue('140');await expect(reps()).toHaveValue('');await expect(rir()).toHaveValue('3');await expect(panel()).toContainText('Last time');
 await panel().getByText('History',{exact:true}).click();assert.equal(await page.getByText('Original units',{exact:true}).count(),0);
 await page.screenshot({path:dir+'desktop-history.png',fullPage:true});
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:dir+'mobile-'+width+'.png',fullPage:true});const sizes=await panel().getByRole('button',{name:/^[0-5] RIR$/}).evaluateAll(xs=>xs.map(x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})));assert(sizes.every(s=>s.w>=44&&s.h>=44))}
 await page.setViewportSize({width:1360,height:1000});await select(4);await expect(load()).toHaveValue('');await select(6);await expect(load()).toHaveValue('');await panel().getByRole('button',{name:'Decrease load by 10 lb'}).click();await expect(load()).toHaveValue('');await select(9);await expect(load()).toHaveValue('');
 checks.push('Prescription priority 60 kg → 130 lb; latest eligible corrected working history → 140 lb; no-history and incompatible history blank; UI removals and 44px RIR controls at 320/390/1360');
 await select(0);await load().fill('137.25');await reps().fill('9');await rir().fill('0');await save();await expect(chips().nth(1)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('137.25');await expect(reps()).toHaveValue('9');await expect(rir()).toHaveValue('0');assert.deepEqual((await row(0)).result,{reps:{value:9,basis:'total'},measurement:{kind:'externalLoad',value:'137.25',unit:'lb',convention:'barbellTotal',zeroMeaning:'validZero'},rir:'0'});
 assert.equal(await page.evaluate(()=>document.activeElement?.tagName),'H3');await expect(page.getByRole('complementary',{name:'Rest timer'})).toBeVisible();
 await select(2);await load().fill('');await reps().fill('11');await select(1);await load().fill('0');await reps().fill('0');await rir().fill('');await save();await expect(chips().nth(2)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('');await expect(reps()).toHaveValue('11');await expect(rir()).toHaveValue('0');await save();await expect(chips().nth(3)).toHaveAttribute('aria-pressed','true');
 assert.equal((await row(1)).result.measurement.value,'0');assert.equal((await row(1)).result.rir,null);assert.equal((await row(2)).result.measurement,null);
 await load().fill('151.125');await reps().fill('7');await rir().fill('4');await save();await expect(chips().nth(4)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('151.125');await expect(reps()).toHaveValue('7');await expect(rir()).toHaveValue('4');
 await select(5);await expect(load()).toHaveValue('151.125');await load().fill('199.125');await save();await expect(chips().nth(6)).toHaveAttribute('aria-pressed','true');await select(4);await expect(load()).toHaveValue('151.125');await save();await expect(chips().nth(6)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('');
 checks.push('Exact browser payload → PostgreSQL result/readback; pre-mounted next defaults update; user-cleared/typed draft wins; zero and missing values; out-of-order logging uses saved target order within the exercise');
 await load().fill('22.25');await reps().fill('');await rir().fill('');await save();await expect(chips().nth(7)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('22.25');await expect(reps()).toHaveValue('');await expect(rir()).toHaveValue('');
 // Hold a real accepted response while selecting and editing a different target.
 await select(9);await load().fill('31.25');await reps().fill('6');let release!:()=>void,reached!:()=>void;const held=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>release=r);
 await page.route('**/api/trainer2/executions/results',async route=>{const response=await route.fetch();reached();await gate;await route.fulfill({response})},{times:1});
 await panel().getByRole('button',{name:'Log set',exact:true}).click();await held;await select(8);await load().fill('28.375');await reps().fill('12');release();await expect(chips().nth(9)).toHaveAttribute('aria-label',/recorded$/);await expect(chips().nth(8)).toHaveAttribute('aria-pressed','true');await expect(load()).toHaveValue('28.375');
 let original='';await page.route('**/api/trainer2/executions/results',async route=>{original=route.request().postData()!;await route.fetch();await route.abort('failed')},{times:1});await panel().getByRole('button',{name:'Log set',exact:true}).click();await expect(panel().getByRole('button',{name:'Retry save'})).toBeEnabled();await page.reload();await expect(panel().getByRole('button',{name:'Retry save'})).toBeEnabled();const retry=page.waitForRequest(r=>r.url().endsWith('/executions/results')&&r.method()==='POST');await panel().getByRole('button',{name:'Retry save'}).click();assert.equal((await retry).postData(),original);await expect(chips().nth(10)).toHaveAttribute('aria-pressed','true');assert.equal((await read()).history.filter((r:any)=>r.actionId===JSON.parse(original).actionId).length,1);
 await select(0);await load().fill('138.375');await reps().fill('10');await panel().getByRole('button',{name:'5 RIR',exact:true}).click();assert.equal(await panel().getByLabel(/correction reason/).count(),0);await save();await expect(panel()).toContainText('Saved v2: 138.375');assert.equal((await row(0)).reason,null);assert(!('reason' in commands.at(-1).intent));
 const historyCount=(await read()).history.length;await panel().getByRole('button',{name:'Update set'}).click();await expect(panel()).toContainText('No values changed');assert.equal((await read()).history.length,historyCount);await page.reload();await expect(load()).toHaveValue('138.375');await expect(reps()).toHaveValue('10');
 const tab=await context.newPage();await tab.goto(page.url());await select(0,tab);await reps(tab).fill('6');await reps().fill('8');await save();await expect(panel()).toContainText('Saved v3');await panel(tab).getByRole('button',{name:'Update set'}).click();await expect(panel(tab).getByRole('button',{name:'Review latest result'})).toBeVisible();await expect(reps(tab)).toHaveValue('6');await panel(tab).getByRole('button',{name:'Review latest result'}).click();await panel(tab).getByRole('button',{name:'Use this version for my correction'}).click();await save(tab);await expect(panel(tab)).toContainText('Saved v4');await tab.close();
 checks.push('Late accepted responses preserve selected target and typing; lost response/reload retries exact command once; current corrections omit reason, preserve versions and stale-edit review');
 // Real historical edit and no-op of an unchanged converted kg result.
 const historic=await context.newPage();await historic.goto(base+'/trainer2/dev/executions/'+ready.completed[0].executionId);const first=historic.getByLabel('Set 1 actual result',{exact:true}).first();await first.getByRole('button',{name:'Correct result'}).click();await expect(first.getByLabel(/Actual load$/)).toHaveValue('99.21');const beforeHistorical=await get('/api/trainer2/executions/'+ready.completed[0].executionId);await first.getByRole('button',{name:'Save correction'}).click();await expect(first).toContainText('No values changed');assert.deepEqual((await get('/api/trainer2/executions/'+ready.completed[0].executionId)).history,beforeHistorical.history);
 await first.getByRole('button',{name:'Correct result'}).click();await first.getByLabel(/Actual reps/).fill('8');await first.getByRole('button',{name:'Save correction'}).click();await expect(first).toContainText('Saved v2');const corrected=await get('/api/trainer2/executions/'+ready.completed[0].executionId);const targetId=corrected.initial.positions[0].targets[0].id;const afterHistorical=corrected.results.find((r:any)=>r.targetId===targetId);assert.equal(afterHistorical.reason,null);assert.equal(afterHistorical.result.measurement.unit,'kg');assert.equal(afterHistorical.result.measurement.value,'45');await historic.screenshot({path:dir+'historical-edit.png',fullPage:true});await historic.close();
 checks.push('Historical reason-free correction retains original kg bytes and immutable history; unchanged converted result is a no-op');
 await page.reload();await select(0);await page.screenshot({path:dir+'desktop-edit.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'mobile-edit.png',fullPage:true});
 const finishedRead=await read();assert.deepEqual(finishedRead.initial,initial.initial);
 const persisted=JSON.parse(sql(`SELECT coalesce(json_agg(row_to_json(r)),'[]'::json) FROM "Trainer2SetResultRevision" r WHERE "executionId"='${id}'`));assert.equal(persisted.length,finishedRead.history.length);for(const r of finishedRead.history){const db=persisted.find((p:any)=>p.targetId===r.targetId&&p.version===r.version);assert.deepEqual(db.result,r.result);assert.equal(db.reason,r.reason);assert.equal(db.actionId,r.actionId)}
 const actionRows=JSON.parse(sql(`SELECT json_agg(json_build_object('envelope',a."submittedEnvelope"::jsonb,'result',r.result,'reason',r.reason)) FROM "Trainer2SetResultRevision" r JOIN "Trainer2DurableAction" a ON a."accountId"=r."accountId" AND a."actionId"=r."actionId" WHERE r."executionId"='${id}'`));for(const r of actionRows){assert.deepEqual(r.envelope.intent.result,r.result);assert.equal(r.envelope.intent.reason??null,r.reason)}
 await page.getByRole('button',{name:'Finish workout',exact:true}).click();await expect(page.getByRole('button',{name:'Finish with unrecorded sets'})).toBeVisible();await page.getByRole('button',{name:'Keep working'}).click();await page.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('button',{name:'Finish with unrecorded sets'}).click();await expect(page).toHaveURL(/drafts\?planId=/);assert.equal((await read()).lifecycle,'Finished');
 checks.push('Immutable initial prescription; every persisted revision matches submitted command and readback; explicit incomplete finish acknowledgement and navigation home');
 assert.deepEqual(errors,[]);writeFileSync(dir+'browser.json',JSON.stringify({at:new Date().toISOString(),source,sourceAfter:verificationSource(),base,container,database,executionId:id,checks,commands,persisted,actionRows,finishedRead,afterHistorical,errors},null,2));console.log(checks.join('\n'));
 }finally{await browser.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
