// Synthetic browser verification against this task's explicitly supplied local demo only.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { chromium, expect, type Page } from '@playwright/test';
import { verificationSource } from '../../scripts/trainer2/verification-source';

async function main() {
const [base, confirmation] = process.argv.slice(2);
assert(confirmation === '--confirm-synthetic-trial' && /^http:\/\/127\.0\.0\.1:\d+$/.test(base));
const ready = JSON.parse(readFileSync('artifacts/trainer2/training-ui-evidence/demo-ready.json', 'utf8'));
assert.equal(new URL(ready.url).origin, base);
const dir = 'artifacts/trainer2/training-ui-evidence/';
const source = verificationSource();
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1360, height: 1000 } });
const page = await context.newPage();
const errors: string[] = [], passes: string[] = [];
page.on('pageerror', e => errors.push(e.message));
page.on('dialog', d => void d.accept());
const shot = async (p: Page, name: string) => { await p.screenshot({ path: dir + name + '.png', fullPage: true }); };
const firstRow = (p: Page) => p.locator('[aria-label="Set 1 actual result"]').first();
const get = async (path: string) => { const r = await context.request.get(base + path); assert.equal(r.status(), 200); return r.json(); };
try {
  await page.goto(ready.url);
  await expect(page.getByText('Week 2 of 5 · Accumulation')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start workout', exact: true })).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Save plan' })).toHaveCount(0);
  await expect(page.getByRole('article')).toHaveCount(4);
  await shot(page, 'home-desktop');
  const beforeBrowse = await get(`/api/trainer2/plans/${ready.planId}/next`);
  await page.getByRole('link', { name: 'View Program' }).click();
  await expect(page.getByRole('article')).toHaveCount(20);
  await expect(page.getByRole('link', { name: 'View results' })).toHaveCount(4);
  await shot(page, 'program-desktop');
  await page.getByRole('link', { name: 'View results' }).first().click();
  await expect(page.getByRole('heading', { name: 'Workout finished', exact: true })).toBeVisible();
  await expect(firstRow(page)).toContainText('8 reps total');
  await expect(page.getByRole('button', { name: 'Start workout', exact: true })).toHaveCount(0);
  assert.deepEqual(await get(`/api/trainer2/plans/${ready.planId}/next`), beforeBrowse);
  passes.push('Home position and Program/completed browsing are read-only; corrected Week 1 result is visible');
  await page.goto(ready.url);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Start workout', exact: true })).toBeEnabled();
  await shot(page, 'home-mobile');
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name: 'Start workout', exact: true }).click();
  await expect(page).toHaveURL(/executions\//);
  const executionUrl = page.url(), executionId = executionUrl.split('/').at(-1)!;
  await expect(page.getByRole('heading', { name: 'Workout in progress' })).toBeVisible();
  await expect(page.locator('aside').first()).toContainText('Previous · Lower A');
  await expect(page.locator('aside').first()).toContainText('8 reps total');
  const initial = await get(`/api/trainer2/executions/${executionId}`);
  assert.equal(initial.previous[0].executionId, ready.completed[0].executionId);
  assert.equal(initial.previous[0].results[0].version, 2);
  await shot(page, 'logging-mobile-empty');
  const row = firstRow(page);
  await expect(row.getByLabel('Set 1 Actual reps')).toHaveAttribute('inputmode', 'numeric');
  await expect(row.getByLabel('Set 1 Actual load', { exact: true })).toHaveAttribute('inputmode', 'decimal');
  await row.getByLabel('Set 1 Actual load', { exact: true }).fill('72.5');
  await row.getByLabel('Set 1 Actual reps').fill('8');
  await row.getByLabel('Set 1 Actual RIR (optional)').fill('2');
  await row.locator('summary').click(); await row.getByLabel('Set 1 load unit').selectOption('kg');
  await expect(page.getByRole('button', { name: 'Finish workout', exact: true })).toBeDisabled();
  await page.reload();
  await expect(firstRow(page).getByLabel('Set 1 Actual load', { exact: true })).toHaveValue('72.5');
  await firstRow(page).getByRole('button', { name: 'Record set' }).click();
  await expect(firstRow(page)).toContainText('Saved v1');
  passes.push('Compact numeric entry, pending-input finish guard and same-tab reload preserve actual input');
  await firstRow(page).getByRole('button', { name: 'Edit result' }).click();
  await firstRow(page).getByLabel('Set 1 Actual reps').fill('9');
  await firstRow(page).getByLabel('Set 1 correction reason').fill('Synthetic correction');
  await firstRow(page).getByRole('button', { name: 'Save correction' }).click();
  await expect(firstRow(page)).toContainText('Saved v2');
  await firstRow(page).getByRole('button', { name: 'Edit result' }).click();
  await firstRow(page).getByLabel('Set 1 correction reason').fill('Erroneous synthetic entry');
  await firstRow(page).getByRole('button', { name: 'Clear erroneous result' }).click();
  await expect(firstRow(page)).toContainText('Saved v3: Cleared');
  await firstRow(page).getByRole('button', { name: 'Re-record result' }).click();
  await firstRow(page).locator('summary').click(); await firstRow(page).getByLabel('Set 1 load unit').selectOption('kg');
  await firstRow(page).getByLabel('Set 1 Actual load', { exact: true }).fill('0');
  await firstRow(page).getByLabel('Set 1 Actual reps').fill('0');
  await firstRow(page).getByLabel('Set 1 correction reason').fill('Explicit zero control');
  await firstRow(page).getByRole('button', { name: 'Save correction' }).click();
  await expect(firstRow(page)).toContainText('Saved v4');
  assert.equal((await get(`/api/trainer2/executions/${executionId}`)).results[0].result.reps.value, 0);
  passes.push('Correction, explicit clear/re-record, valid zero, immutable starting capture');
  const tab = await context.newPage(); tab.on('dialog', d => void d.accept()); await tab.goto(executionUrl);
  await firstRow(tab).getByRole('button', { name: 'Edit result' }).click();
  await firstRow(tab).getByLabel('Set 1 Actual reps').fill('6');
  await firstRow(tab).getByLabel('Set 1 correction reason').fill('Stale tab input');
  await firstRow(page).getByRole('button', { name: 'Edit result' }).click();
  await firstRow(page).getByLabel('Set 1 Actual reps').fill('7');
  await firstRow(page).getByLabel('Set 1 correction reason').fill('First tab correction');
  await firstRow(page).getByRole('button', { name: 'Save correction' }).click();
  await expect(firstRow(page)).toContainText('Saved v5');
  await firstRow(tab).getByRole('button', { name: 'Save correction' }).click();
  await expect(firstRow(tab)).toContainText('Result changed elsewhere');
  await firstRow(tab).getByRole('button', { name: 'Review latest result' }).click();
  await firstRow(tab).getByRole('button', { name: 'Use this version for my correction' }).click();
  await firstRow(tab).getByRole('button', { name: 'Save correction' }).click();
  await expect(firstRow(tab)).toContainText('Saved v6');
  await tab.close();
  await page.getByRole('button', { name: 'Refresh saved results' }).click();
  await expect(firstRow(page)).toContainText('Saved v6');
  passes.push('Two-tab stale correction retains input and requires explicit review/rebase/save');
  const second = page.locator('[aria-label="Set 2 actual result"]').first();
  await second.getByLabel('Set 2 Actual load', { exact: true }).fill('70'); await second.getByLabel('Set 2 Actual reps').fill('10');
  const envelopes: string[] = [];
  await page.route('**/api/trainer2/executions/results', async route => { envelopes.push(route.request().postData()!); await route.fetch(); await route.abort(); }, { times: 1 });
  await second.getByRole('button', { name: 'Record set' }).click();
  await expect(second.getByRole('button', { name: 'Check again' })).toBeEnabled();
  await page.reload();
  page.on('request', r => { if (r.url().endsWith('/executions/results')) envelopes.push(r.postData()!); });
  await page.locator('[aria-label="Set 2 actual result"]').first().getByRole('button', { name: 'Check again' }).click();
  await expect(page.locator('[aria-label="Set 2 actual result"]').first()).toContainText('Saved v1');
  assert.equal(envelopes[0], envelopes[1]);
  await expect(page.locator('[aria-label="Set 2 actual result"]').first().getByRole('button', { name: 'Check again' })).toHaveCount(0);
  passes.push('Lost committed result response survives refresh with byte-identical retry');
  await page.setViewportSize({ width: 1360, height: 1000 }); await shot(page, 'logging-desktop');
  await page.setViewportSize({ width: 390, height: 844 }); await shot(page, 'logging-mobile'); await page.screenshot({path: dir + 'logging-mobile-viewport.png'});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const beforeFinish = await get(`/api/trainer2/executions/${executionId}`);
  assert.deepEqual(beforeFinish.initial, initial.initial);
  await page.route('**/api/trainer2/executions/finish', async route => { await route.fetch(); await route.abort(); }, { times: 1 });
  await page.getByRole('button', { name: 'Finish workout', exact: true }).click();
  await page.getByRole('button', { name: 'Finish with unrecorded sets' }).click();
  await expect(page.getByRole('button', { name: 'Check finish again' })).toBeEnabled();
  assert.equal(page.url(), executionUrl);
  await page.reload(); await page.getByRole('button', { name: 'Check finish again' }).click();
  await expect(page).toHaveURL(ready.url);
  await expect(page.getByRole('status')).toContainText('Workout finished.');
  await expect(page.getByText(/1 of 4 workouts completed · 0 skipped/)).toBeVisible();
  await shot(page, 'post-finish-mobile');
  await page.setViewportSize({ width: 1360, height: 1000 }); await shot(page, 'post-finish-desktop');
  passes.push('Lost finish response stays on execution; successful exact retry returns home after readback with correct weekly status');
  await page.getByRole('button', { name: 'Skip workout', exact: true }).click();
  await expect(page.getByRole('group', { name: 'Confirm skip' })).toContainText('Week 2 · Workout 6 of 20');
  await shot(page, 'skip-confirm');
  await page.getByRole('button', { name: 'Confirm skip' }).click();
  await expect(page.getByText(/1 of 4 workouts completed · 1 skipped/)).toBeVisible();
  passes.push('Skip identifies duplicate workout by week and saved program position; skipped is separate from completed');
  assert.deepEqual(errors, []);
  writeFileSync(dir + 'browser.json', JSON.stringify({ source, finishedAt: new Date().toISOString(), browser: browser.version(), mobile: '390x844 viewport emulation', executionUrl, planId: ready.planId, passes, errors }, null, 2));
  console.log(passes.join('\n'));
} catch (e) { await shot(page, 'browser-failure'); throw e; }
finally { await browser.close(); }

}
void main().catch(e => { console.error(e); process.exitCode = 1; });
