import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import type { Page } from '@playwright/test';
import type { readDraft } from '../../src/lib/api/trainer2/planning';
import { identities } from '../../src/lib/engine/trainer2/planning';
export async function verifyEditorBrowser(tab: Page, read: (id: string) => ReturnType<typeof readDraft>) {
  const button = (name: string) => tab.getByRole('button', { name, exact: true });
  const saved = () => tab.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
  const save = async () => { await button('Save plan').click(); await saved(); };
  const row = (i: number) => tab.getByRole('region', { name: 'Exercise ' + i, exact: true });
  const shot = async (name: string) => { await tab.evaluate(()=>window.scrollTo(0,0)); await tab.screenshot({path:resolve('artifacts/trainer2/'+name+'.png'),fullPage:true}); };
  await tab.setViewportSize({ width: 1280, height: 950 });
  await tab.getByRole('tab', { name: 'Lower A', exact: true }).waitFor();
  assert.equal(await tab.getByRole('tab').count(), 4);
  assert.equal(new URL(tab.url()).searchParams.get('planId'), null);
  for (const [name,count] of [['Lower A',5],['Upper A',6],['Lower B',5],['Upper B',7]] as const) { await tab.getByRole('tab',{name,exact:true}).click(); assert.equal(await tab.getByRole('region',{name:/^Exercise /}).count(),count); }
  await tab.getByRole('tab',{name:'Lower A',exact:true}).click();
  await shot('initial-plan');
  await row(1).getByRole('button',{name:'Swap',exact:true}).click();
  const dialog=tab.getByRole('dialog',{name:'Swap exercise',exact:true});
  assert(await dialog.getByRole('button',{name:/Front Squat/}).isVisible());
  await shot('swap-picker');
  await tab.getByLabel('Search exercises',{exact:true}).focus(); await tab.keyboard.press('Tab'); await tab.keyboard.press('Tab'); await tab.keyboard.press('ArrowDown'); await tab.keyboard.press('ArrowUp'); assert.equal(await tab.evaluate(()=>document.activeElement?.textContent?.includes('Front Squat')),true); await tab.keyboard.press('Enter');
  await row(2).getByRole('button',{name:'Swap',exact:true}).click();
  await dialog.getByRole('button',{name:/Dumbbell Romanian Deadlift/}).click();
  await row(2).getByRole('button',{name:'Swap',exact:true}).click();
  await tab.getByLabel('Search exercises',{exact:true}).fill('RDL');
  assert(await dialog.getByRole('button',{name:/Barbell Romanian Deadlift/}).isVisible());
  await shot('search-results');
  await tab.getByLabel('Search exercises',{exact:true}).fill('zz-no-result');assert(await dialog.getByRole('status').isVisible());
  await tab.keyboard.press('Escape');
  await save();
  const planId = new URL(tab.url()).searchParams.get('planId')!;
  const first=(await read(planId))!;
  assert.deepEqual(first.intent.builder!.workouts.map(w=>w.rows.length),[5,6,5,7]);
  assert.deepEqual(first.intent.occurrences.filter(o=>o.name==='Lower A').map(o=>[o.positions[0].targets.length,o.positions[0].targets[0].rir]),[[3,'3'],[3,'3'],[3,'2'],[3,'1'],[2,'4']]);
  assert.equal(first.intent.occurrences[0].positions[0].exercise.name,'Front Squat');
  assert.equal(first.intent.occurrences[0].positions[1].exercise.name,'Dumbbell Romanian Deadlift');
  await tab.getByLabel('Edit scope').selectOption('2');
  // A real input event explicitly sets the same value; equal values remain overrides.
  await tab.getByLabel('Exercise 1 reps min',{exact:true}).fill('7');
  await tab.getByLabel('Exercise 1 reps min',{exact:true}).fill('6');
  await tab.getByLabel('Edit scope').selectOption('all');
  await tab.getByLabel('Exercise 1 reps min',{exact:true}).fill('8');
  await row(1).getByText('Effort, role & optional details',{exact:true}).click();
  await row(1).getByLabel('Rest seconds (blank = unspecified)',{exact:true}).fill('120');
  await save();
  const edited=(await read(planId))!;
  assert.equal(edited.intent.occurrences[8].positions[0].targets[0].reps.min,6);
  assert.equal(edited.intent.occurrences[8].positions[0].targets[0].restSeconds,'120');
  assert.equal(edited.intent.occurrences[0].positions[0].targets[0].reps.min,8);
  assert(edited.intent.occurrences[8].overrides!.fields[edited.intent.occurrences[8].positions[0].id].includes('reps'));
  await tab.reload();await saved();
  await button('View all 5 weeks').click();await shot('five-weeks');
  await button('Hide weeks').click();
  await tab.setViewportSize({width:390,height:844});await shot('mobile-editor');
  assert(await tab.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await row(1).getByRole('button',{name:'Swap',exact:true}).tap();await shot('mobile-picker');
  await tab.getByLabel('Filter picker equipment').selectOption('Dumbbell');
  assert(await tab.getByRole('dialog').getByRole('button',{name:/Goblet Squat/}).isVisible());
  await button('Close picker').tap();
  await tab.getByLabel('Edit scope').selectOption('2');
  await button('Reset reps override').tap();
  await tab.getByLabel('Edit scope').selectOption('all');
  await row(1).getByRole('button',{name:'Move down',exact:true}).tap();await save();
  const reordered=(await read(planId))!;
  const initialIds=first.intent.occurrences[0].positions.map(p=>p.id);[initialIds[0],initialIds[1]]=[initialIds[1],initialIds[0]];
  assert.deepEqual(reordered.intent.occurrences[0].positions.map(p=>p.id),initialIds);
  assert.equal(reordered.intent.occurrences[8].positions[1].targets[0].reps.min,8);
  await tab.reload();await saved();assert.deepEqual((await read(planId))!.intent,reordered.intent);
  assert(await button('Save plan').isDisabled());
  await tab.getByText('Review saved plan',{exact:true}).click();
  assert((await tab.getByLabel('Saved plan review').innerText()).includes('Week 5 · Deload'));
  assert((await tab.getByLabel('Saved plan review').innerText()).includes('4 reps left'));
  await tab.setViewportSize({width:1280,height:950});
  const other = await tab.context().newPage();
  try {
    await other.goto(tab.url()); await other.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
    await other.getByLabel('Plan name', { exact: true }).fill('Other browser');
    await other.getByRole('button', { name: 'Save plan', exact: true }).click();
    await other.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
    await tab.getByLabel('Plan name', { exact: true }).fill('Losing browser intent'); await button('Save plan').click();
    await tab.getByRole('status').filter({ hasText: 'changed in another tab' }).waitFor();
    assert.equal(await tab.getByLabel('Plan name', { exact: true }).inputValue(), 'Losing browser intent');
    await button('Reload latest version').click(); await saved();
    assert(await tab.getByLabel('Plan name', { exact: true }).isDisabled());
    await button('Continue from latest plan').click();
  } finally { await other.close(); }
  const bodies: string[] = [];
  await tab.route('**/api/trainer2/drafts/edit', async route => {
    bodies.push(route.request().postData()!);
    if (bodies.length === 1) { assert.equal((await route.fetch()).status(), 200); await route.abort('failed'); }
    else await route.continue();
  });
  await tab.getByLabel('Plan name', { exact: true }).fill('Response loss recovered'); await button('Save plan').click();
  await tab.getByRole('status').filter({ hasText: 'could not be confirmed' }).waitFor();
  assert(await button('Save plan').isDisabled());
  await button('Check again').click(); await saved();
  assert.equal(bodies.length, 2); assert.equal(bodies[0], bodies[1]);
  assert.equal((await read(planId))!.revisionNumber, 5);
  assert.deepEqual(identities((await read(planId))!.intent).map(i => i.id).sort(), identities(first.intent).map(i => i.id).sort());
  await tab.unroute('**/api/trainer2/drafts/edit');
  const text = await tab.locator('main').innerText();
  for (const forbidden of ['Create finite draft', 'Save name revision', 'Current head', 'Command envelope']) assert(!text.includes(forbidden));
  const scratch = await tab.context().newPage();
  try {
    await scratch.goto(new URL('/trainer2/dev/drafts', tab.url()).href);
    await scratch.getByRole('button', { name: 'Start blank', exact: true }).click();
    await scratch.getByRole('button', { name: 'Keep my edits', exact: true }).click();
    assert.equal(await scratch.getByRole('region', { name: /^Exercise / }).count(), 5);
    await scratch.getByLabel('Edit scope').selectOption('2');
    await scratch.getByRole('region', { name: 'Exercise 1', exact: true }).getByRole('button', { name: 'Swap', exact: true }).click();
    await scratch.getByRole('dialog').getByRole('button', { name: /Bulgarian Split Squat/ }).click();
    await scratch.getByRole('button', { name: 'Save plan', exact: true }).click();
    await scratch.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
    const scratchId = new URL(scratch.url()).searchParams.get('planId')!;
    const swapped = (await read(scratchId))!.intent;
    assert.equal(swapped.occurrences[8].positions[0].targets[0].reps.basis, 'perSide');
    assert.equal(swapped.occurrences[0].positions[0].targets[0].reps.basis, 'total');
    await scratch.reload();
    await scratch.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
    await scratch.getByLabel('Edit scope').selectOption('2');
    await scratch.getByRole('button', { name: 'Reset swap, reps & weight override', exact: true }).click();
    await scratch.getByRole('button', { name: 'Save plan', exact: true }).click();
    await scratch.getByRole('status').filter({ hasText: /^Saved$/ }).waitFor();
    assert.equal((await read(scratchId))!.intent.occurrences[8].positions[0].targets[0].reps.basis, 'total');
  } finally { await scratch.close(); }
  return planId;
}
