import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { PrismaClient } from '@prisma/client';
import type { Pool } from 'pg';
import { chromium, expect as playwrightExpect } from '@playwright/test';
import { createDraft, readDraft, ActionCollision, type ServerPrincipal } from '../../src/lib/api/trainer2/planning';
import { activatePlan } from '../../src/lib/api/trainer2/activation';
import { startOccurrence, readExecution, readNextWorkout } from '../../src/lib/api/trainer2/execution';
import { skipOccurrence } from '../../src/lib/api/trainer2/skip-occurrence';
import { discardEmptyExecution } from '../../src/lib/api/trainer2/discard-execution';
import { finishExecution } from '../../src/lib/api/trainer2/workout-finish';
import { saveSetResult, correctHistoricalSetResult } from '../../src/lib/api/trainer2/set-results';
import { reviewedResults } from '../../src/lib/trainer2-contracts/workout-finish';
import { nextWorkoutRead, type ExecutionRead } from '../../src/lib/trainer2-contracts/execution';
import type { SkipOccurrenceCommand } from '../../src/lib/trainer2-contracts/skip-occurrence';
import { createHypertrophyPlan } from '../../src/lib/engine/trainer2/plan-builder';
import { commandBinding } from '../../src/lib/api/trainer2/integrity';
import { verifySkipUpgrade } from './verify-skip-upgrade';
const expect = playwrightExpect.configure({ timeout: 30_000 });

export async function verifySkipWorkout(db: PrismaClient, reader: PrismaClient, owner: PrismaClient, admin: Pool,
  browserPrincipal: ServerPrincipal, startWeb: () => Promise<string>, restartWeb: () => Promise<string>, ownerUrl: string, runtimeUrl: string,
  command: (exe: string, args: string[], env?: NodeJS.ProcessEnv) => string) {
  const results: string[] = [], evidence: unknown[] = [];
  const pass = (name: string) => { results.push(name); console.log('PASS '+name); writeFileSync(resolve('artifacts/trainer2/skip-progress.json'),JSON.stringify({results,evidence},null,2)); };
  const envelope = (p: ServerPrincipal) => ({ schemaVersion: 1 as const, actionId: randomUUID(), deviceId: randomUUID(), originatingAccountId: p.accountId, ownershipEpoch: 0, dependsOn: [] });
  const ok = <T,>(r: { outcome: { status: string; result?: T } }): T => { assert.equal(r.outcome.status,'Accepted',JSON.stringify(r)); return r.outcome.result!; };
  const account = async (write = owner) => { const p={accountId:randomUUID(),issuer:'skip-synthetic',subject:randomUUID()}; await write.user.create({data:{id:p.accountId,email:`${p.subject}@trainer2.invalid`}}); await write.trainer2AccountPrincipal.create({data:{id:randomUUID(),...p}});return p; };
  const create = async (p: ServerPrincipal, count=3, write=db, read=reader, optional=false) => {
    const template=createHypertrophyPlan(); const stages=[{id:randomUUID(),name:'Week 2'},{id:randomUUID(),name:'Week 1'}];
    const intent={schemaVersion:1 as const,name:'Synthetic skip plan',endpoint:template.endpoint,progression:template.progression,stages,
      occurrences:Array.from({length:count},(_,i)=>({id:randomUUID(),stageId:stages[i%2].id,name:'Same workout',positions:[{id:randomUUID(),exercise:{kind:'authoredDescription' as const,name:i%2?'Squat':'Row',variation:''},
        targets:[{id:randomUUID(),required:!optional,classification:'working' as const,reps:{min:8,max:12,basis:'total' as const},measurement:null,rir:null,restSeconds:null}]}]}))};
    const planId=randomUUID();ok(await createDraft(write,p,{...envelope(p),commandType:'CreateDraft',target:{planId},expected:{},intent}));
    const h=(await readDraft(read,p,planId))!;ok(await activatePlan(write,p,{...envelope(p),commandType:'ActivatePlan',target:{planId},expected:{planRevisionId:h.revisionId},intent:{reviewed:h.activation}}));return h;
  };
  const next = async(p:ServerPrincipal,planId:string,read=reader)=>nextWorkoutRead.parse(await readNextWorkout(read,p,planId));
  const skip = async(p:ServerPrincipal,planId:string):Promise<SkipOccurrenceCommand>=>{const n=await next(p,planId);assert(n.occurrence);return {...envelope(p),commandType:'SkipOccurrence',target:{planId,occurrenceId:n.occurrence.id},expected:{planRevisionId:n.revisionId,acceptedSequence:n.acceptedSequence},intent:{}};};
  const start = async(p:ServerPrincipal,planId:string,write=db,read=reader)=>{const n=await readNextWorkout(read,p,planId);assert(n.occurrence);const c={...envelope(p),commandType:'StartOccurrence',target:{planId,occurrenceId:n.occurrence.id},expected:{planRevisionId:n.revisionId,instructionEpoch:n.instructionEpoch},intent:{}};const r=ok(await startOccurrence(write,p,c));return {c,x:(await readExecution(read,p,r.executionId))!};};
  const finish = (p:ServerPrincipal,x:ExecutionRead,write=db)=>finishExecution(write,p,{...envelope(p),commandType:'FinishExecution',target:{executionId:x.executionId},expected:reviewedResults(x),intent:{acknowledgeUnrecorded:true}});
  const discard = (p:ServerPrincipal,x:ExecutionRead)=>({...envelope(p),commandType:'DiscardEmptyExecution',target:{executionId:x.executionId,occurrenceId:x.initial.occurrence.id},expected:reviewedResults(x),intent:{}});
  const record = async(p:ServerPrincipal,x:ExecutionRead,write=db)=>ok(await saveSetResult(write,p,{...envelope(p),commandType:'RecordSetResult',target:{executionId:x.executionId,targetId:x.initial.positions[0].targets[0].id},expected:{resultVersion:0},intent:{result:{reps:{value:0,basis:'total'},measurement:null,rir:null}}}));
  const tables=['Trainer2Plan','Trainer2PlanRevision','Trainer2PlanDecision','Trainer2Identity','Trainer2Execution','Trainer2ExecutionFinish','Trainer2ExecutionDiscard','Trainer2SetResultRevision','Trainer2OccurrenceSkip','Trainer2DurableAction','Trainer2ActionOutcome','Trainer2AccountTrainingState'];
  const snapshot=async(p:ServerPrincipal)=>Object.fromEntries(await Promise.all(tables.map(async t=>[t,(await admin.query(`SELECT to_jsonb(t) row FROM "${t}" t WHERE "accountId"=$1 ORDER BY to_jsonb(t)::text`,[p.accountId])).rows.map(r=>r.row)])));
  const unchangedDomain=(a:Awaited<ReturnType<typeof snapshot>>,b:Awaited<ReturnType<typeof snapshot>>)=>{for(const t of tables.filter(t=>!['Trainer2DurableAction','Trainer2ActionOutcome','Trainer2AccountTrainingState'].includes(t)))assert.deepEqual(b[t],a[t],t);assert.equal(b.Trainer2AccountTrainingState[0].acceptedSequence,a.Trainer2AccountTrainingState[0].acceptedSequence);};
  // Independent oracle reads saved order and terminal rows, never the production selector.
  const oracle=async(p:ServerPrincipal,planId:string)=>{const plan=await owner.trainer2Plan.findUniqueOrThrow({where:{id:planId}});const r=await owner.trainer2PlanRevision.findUniqueOrThrow({where:{id:plan.currentRevisionId}});const order=(r.document as {occurrences:{id:string}[]}).occurrences.map(o=>o.id);
    const terminal=(await admin.query(`SELECT "occurrenceId" FROM "Trainer2Execution" WHERE "accountId"=$1 AND "planId"=$2 AND lifecycle='Finished' UNION SELECT "occurrenceId" FROM "Trainer2OccurrenceSkip" WHERE "accountId"=$1 AND "planId"=$2`,[p.accountId,planId])).rows.map(r=>r.occurrenceId);
    const expected=order.find(id=>!terminal.includes(id))??null;const actual=await next(p,planId);assert.equal(actual.occurrence?.id??null,expected);assert.equal(actual.lifecycle,expected?'Active':'Completed');return expected;};
  async function race<T,U>(p:ServerPrincipal,first:()=>Promise<T>,second:()=>Promise<U>){const lock=await admin.connect();await lock.query('BEGIN');const pid=(await lock.query('SELECT pg_backend_pid() pid')).rows[0].pid;await lock.query('SELECT "accountId" FROM "Trainer2AccountTrainingState" WHERE "accountId"=$1 FOR UPDATE',[p.accountId]);
    const waiting=async(count:number)=>{const deadline=Date.now()+8000;for(;;){const r=await admin.query('WITH RECURSIVE waiting(pid) AS (SELECT pid FROM pg_stat_activity WHERE $1=ANY(pg_blocking_pids(pid)) UNION SELECT a.pid FROM pg_stat_activity a JOIN waiting w ON w.pid=ANY(pg_blocking_pids(a.pid))) SELECT DISTINCT pid,pg_blocking_pids(pid) blockers FROM waiting',[pid]);if(r.rowCount!>=count){evidence.push({queue:{holder:pid,count,waiters:r.rows}});return;}if(Date.now()>deadline)throw Error('Lock queue not observed');await new Promise(r=>setTimeout(r,20));}};
    let a:Promise<T>|undefined,b:Promise<U>|undefined;try{a=first();await waiting(1);b=second();await waiting(2);await lock.query('COMMIT');return await Promise.all([a,b]);}finally{await lock.query('ROLLBACK');lock.release();await Promise.allSettled([a,b].filter(Boolean));}}
  const baseCompatible=(client:PrismaClient):PrismaClient=>new Proxy(client,{get(target,key){if(key==='trainer2OccurrenceSkip')return {findMany:async()=>[]};if(key==='$transaction')return (fn:(tx:PrismaClient)=>Promise<unknown>,options:unknown)=>target.$transaction(tx=>fn(baseCompatible(tx as PrismaClient)),options as never);const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});
  const upgrade=await verifySkipUpgrade(admin,ownerUrl,runtimeUrl,command,async(up,upOwner)=>{
    const p=await account(upOwner),base=baseCompatible(up),h=await create(p,1,base,base);let {x}=await start(p,h.planId,base,base);const r=await record(p,x,base);x=(await readExecution(base,p,x.executionId))!;ok(await finish(p,x,base));
    ok(await correctHistoricalSetResult(base,p,{...envelope(p),commandType:'CorrectHistoricalSetResult',target:{executionId:x.executionId,targetId:r.targetId},expected:{resultVersion:r.version,performedSetId:r.performedSetId},intent:{result:{reps:{value:9,basis:'total'},measurement:null,rir:null},reason:'Correct recorded result'}}));
    const active=await create(p,2,base,base),attempt=await start(p,active.planId,base,base);ok(await discardEmptyExecution(base,p,discard(p,attempt.x)));
    return async()=>{assert.equal((await readExecution(up,p,x.executionId))!.results[0].version,2);assert.equal((await readExecution(up,p,attempt.x.executionId))!.lifecycle,'Discarded');const n=await next(p,active.planId,up);ok(await skipOccurrence(up,p,{...envelope(p),commandType:'SkipOccurrence',target:{planId:active.planId,occurrenceId:n.occurrence!.id},expected:{planRevisionId:n.revisionId,acceptedSequence:n.acceptedSequence},intent:{}}));};
  });pass('Fresh install/redeploy and accepted-base populated schema upgrade preserve active/completed plans, corrected results and discarded attempts');
  for(const count of [1,4]){const p=await account(),h=await create(p,count);for(let i=0;i<count;i++){const c=await skip(p,h.planId),before=await snapshot(p),r=ok(await skipOccurrence(db,p,c));assert.equal(r.planCompleted,i===count-1);const after=await snapshot(p);
    for(const t of tables.filter(t=>!['Trainer2Plan','Trainer2OccurrenceSkip','Trainer2DurableAction','Trainer2ActionOutcome','Trainer2AccountTrainingState'].includes(t)))assert.deepEqual(after[t],before[t],t);
    assert.deepEqual(after.Trainer2Plan,before.Trainer2Plan.map((row: Record<string, unknown>)=>({...row,lifecycle:i===count-1?'Completed':'Active'})));assert.equal(after.Trainer2OccurrenceSkip.length,before.Trainer2OccurrenceSkip.length+1);assert.equal(after.Trainer2DurableAction.length,before.Trainer2DurableAction.length+1);assert.equal(after.Trainer2ActionOutcome.length,before.Trainer2ActionOutcome.length+1);assert.equal(String(after.Trainer2AccountTrainingState[0].acceptedSequence),String(BigInt(before.Trainer2AccountTrainingState[0].acceptedSequence)+BigInt(1)));
    for(const table of ['Trainer2DurableAction','Trainer2ActionOutcome'])assert.deepEqual(after[table].filter((r:{actionId:string})=>r.actionId!==c.actionId),before[table]);
    assert.equal(after.Trainer2Execution.length,0);assert.equal(after.Trainer2SetResultRevision.length,0);
    const fact=after.Trainer2OccurrenceSkip.find((r: {occurrenceId:string})=>r.occurrenceId===c.target.occurrenceId)!;assert.equal(fact.accountId,p.accountId);assert.equal(fact.actionId,c.actionId);assert.deepEqual(fact.expected,c.expected);assert.deepEqual(fact.endpoint.occurrenceIds,h.intent.occurrences.map(o=>o.id));
    assert.equal(await oracle(p,h.planId),h.intent.occurrences[i+1]?.id??null);const replayBefore=await snapshot(p);assert.equal((await skipOccurrence(db,p,c)).replayed,true);assert.deepEqual(await snapshot(p),replayBefore);evidence.push({case:'consecutive skip',count,index:i,before,after});
  }}pass('First/middle/consecutive/final/single skips in duplicate-name saved order and stage boundaries, one advancement and no fabricated performance');
  {
    const p=await account(),h=await create(p,3,db,reader,true),a=await start(p,h.planId);const saved=await record(p,a.x);ok(await finish(p,(await readExecution(reader,p,a.x.executionId))!));
    ok(await correctHistoricalSetResult(db,p,{...envelope(p),commandType:'CorrectHistoricalSetResult',target:{executionId:a.x.executionId,targetId:saved.targetId},expected:{resultVersion:saved.version,performedSetId:saved.performedSetId},intent:{result:{reps:{value:9,basis:'total'},measurement:null,rir:null},reason:'Correct recorded result'}}));
    const c=await skip(p,h.planId),beforeSkip=await snapshot(p);ok(await skipOccurrence(db,p,c));const afterSkip=await snapshot(p);
    for(const t of tables.filter(t=>!['Trainer2OccurrenceSkip','Trainer2DurableAction','Trainer2ActionOutcome','Trainer2AccountTrainingState'].includes(t)))assert.deepEqual(afterSkip[t],beforeSkip[t],t);
    for(const t of ['Trainer2DurableAction','Trainer2ActionOutcome'])assert.deepEqual(afterSkip[t].filter((r:{actionId:string})=>r.actionId!==c.actionId),beforeSkip[t]);
    evidence.push({case:'skip preserves prior completed execution, original finish, historical correction and outcomes',before:beforeSkip,after:afterSkip});
    const b=await start(p,h.planId);ok(await finish(p,b.x));assert.equal(await oracle(p,h.planId),null);
    const before=await snapshot(p);assert.equal((await skipOccurrence(db,p,c)).replayed,true);assert.deepEqual(await snapshot(p),before);
  }pass('Mixed finish/skip endpoint, optional-only workouts remain retained obligations; replay after later start and finish leaves current state unchanged');
  {
    const p=await account(),h=await create(p),old=await skip(p,h.planId),a=await start(p,h.planId),d=discard(p,a.x);ok(await discardEmptyExecution(db,p,d));assert.equal((await skipOccurrence(db,p,old)).outcome.status,'Conflict');
    const before=await snapshot(p),c=await skip(p,h.planId);ok(await skipOccurrence(db,p,c));const after=await snapshot(p);for(const t of ['Trainer2Execution','Trainer2ExecutionDiscard','Trainer2SetResultRevision'])assert.deepEqual(after[t],before[t]);
    const b=await start(p,h.planId);const stable=await snapshot(p);assert.equal((await startOccurrence(db,p,a.c)).replayed,true);assert.equal((await discardEmptyExecution(db,p,d)).replayed,true);assert.equal((await skipOccurrence(db,p,c)).replayed,true);assert.deepEqual(await snapshot(p),stable);assert.equal((await next(p,h.planId)).execution?.executionId,b.x.executionId);evidence.push({case:'discarded skip and historical replays',before,after,stable});
  }pass('Skip after explicit empty discard preserves attempt/audit; stale pre-start binding conflicts; old Start/Discard/Skip replay cannot revive or rewind');
  {
    const p=await account(),q=await account(),h=await create(p),foreign=await create(q),c=await skip(p,h.planId),before=await snapshot(p);
    for(const changed of [{...c,actionId:randomUUID(),target:{...c.target,planId:foreign.planId}},{...c,actionId:randomUUID(),target:{...c.target,occurrenceId:foreign.intent.occurrences[0].id}},{...c,actionId:randomUUID(),target:{...c.target,occurrenceId:h.intent.occurrences[1].id}},{...c,actionId:randomUUID(),expected:{...c.expected,planRevisionId:randomUUID()}},{...c,actionId:randomUUID(),expected:{...c.expected,acceptedSequence:'0'}}])assert.notEqual((await skipOccurrence(db,p,changed)).outcome.status,'Accepted');
    for(const expected of [undefined,{},null,{...c.expected,acceptedSequence:2},{...c.expected,acceptedSequence:'02'}])await assert.rejects(skipOccurrence(db,p,{...c,actionId:randomUUID(),expected}));
    await assert.rejects(skipOccurrence(db,q,c));unchangedDomain(before,await snapshot(p));ok(await skipOccurrence(db,p,c));const stable=await snapshot(p);await assert.rejects(skipOccurrence(db,p,{...c,expected:{...c.expected,acceptedSequence:'0'}}),ActionCollision);assert.deepEqual(await snapshot(p),stable);
    assert.equal((await skipOccurrence(db,p,{...c,actionId:randomUUID(),expected:{...c.expected,acceptedSequence:(await next(p,h.planId)).acceptedSequence}})).outcome.status,'Conflict');
    const started=await start(p,h.planId),live=await skip(p,h.planId),liveBefore=await snapshot(p);assert.equal((await skipOccurrence(db,p,live)).outcome.status,'Conflict');unchangedDomain(liveBefore,await snapshot(p));await record(p,started.x);const recorded=await skip(p,h.planId);assert.equal((await skipOccurrence(db,p,recorded)).outcome.status,'Conflict');ok(await finish(p,(await readExecution(reader,p,started.x.executionId))!));
    const finishedBefore=await snapshot(p);assert.equal((await skipOccurrence(db,p,{...await skip(p,h.planId),target:{planId:h.planId,occurrenceId:started.x.initial.occurrence.id}})).outcome.status,'Conflict');unchangedDomain(finishedBefore,await snapshot(p));
  }pass('Wrong account/plan/revision/occurrence, future target, missing/malformed/stale bindings, changed identity payload, live empty/recorded and completed/skipped rejection have no domain effects');
  for(const skipFirst of [true,false]){const p=await account(),h=await create(p),s=await skip(p,h.planId),n=await next(p,h.planId),c={...envelope(p),commandType:'StartOccurrence',target:s.target,expected:{planRevisionId:n.revisionId,instructionEpoch:n.instructionEpoch},intent:{}};
    const a=()=>skipOccurrence(db,p,s),b=()=>startOccurrence(db,p,c);const [first,second]=await race<Awaited<ReturnType<typeof a>>|Awaited<ReturnType<typeof b>>,Awaited<ReturnType<typeof a>>|Awaited<ReturnType<typeof b>>>(p,skipFirst?a:b,skipFirst?b:a);assert.equal(first.outcome.status,'Accepted');assert.equal(second.outcome.status,'Conflict');assert.equal(await owner.trainer2OccurrenceSkip.count({where:{accountId:p.accountId}}),skipFirst?1:0);assert.equal(await owner.trainer2Execution.count({where:{accountId:p.accountId}}),skipFirst?0:1);await oracle(p,h.planId);evidence.push({case:'skip/start race',skipFirst,first,second,state:await snapshot(p)});
  }
  for(const same of [true,false]){const p=await account(),h=await create(p),s=await skip(p,h.planId);const [a,b]=await race(p,()=>skipOccurrence(db,p,s),()=>skipOccurrence(db,p,same?s:{...s,actionId:randomUUID()}));ok(a);assert.equal(b.outcome.status,same?'Accepted':'Conflict');if(same){assert.equal(b.replayed,true);assert.deepEqual(a.outcome,b.outcome);}assert.equal(await owner.trainer2OccurrenceSkip.count({where:{accountId:p.accountId}}),1);await oracle(p,h.planId);}
  for(const operation of ['finish','discard'] as const)for(const skipFirst of [true,false]){
    const p=await account(),h=await create(p),a=await start(p,h.planId),c=await skip(p,h.planId);
    const skipCall=()=>skipOccurrence(db,p,c), other=()=>operation==='finish'?finish(p,a.x):discardEmptyExecution(db,p,discard(p,a.x));
    const [first,second]=await race<Awaited<ReturnType<typeof skipCall>>|Awaited<ReturnType<typeof other>>,Awaited<ReturnType<typeof skipCall>>|Awaited<ReturnType<typeof other>>>(p,skipFirst?skipCall:other,skipFirst?other:skipCall);
    assert.equal((skipFirst?first:second).outcome.status,'Conflict');assert.equal((skipFirst?second:first).outcome.status,'Accepted');
    assert.equal(await owner.trainer2OccurrenceSkip.count({where:{accountId:p.accountId}}),0);await oracle(p,h.planId);
    evidence.push({case:'skip/live lifecycle race',operation,skipFirst,first,second});
  }
  pass('Observed PostgreSQL blocking chains: Skip/Start, Skip/Finish and Skip/Discard both commit orders, distinct Skip commands and concurrent exact retries');
  for(const table of ['Trainer2Plan','Trainer2AccountTrainingState','Trainer2ActionOutcome']){const p=await account(),h=await create(p,1),c=await skip(p,h.planId),before=await snapshot(p);
    await admin.query(`CREATE FUNCTION skip_test_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."accountId"='${p.accountId}' THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$; CREATE TRIGGER skip_test_fault BEFORE ${table==='Trainer2ActionOutcome'?'INSERT':'UPDATE'} ON "${table}" FOR EACH ROW EXECUTE FUNCTION skip_test_fault()`);
    try{await assert.rejects(skipOccurrence(db,p,c));}finally{await admin.query(`DROP TRIGGER skip_test_fault ON "${table}"; DROP FUNCTION skip_test_fault()`);}assert.deepEqual(await snapshot(p),before);ok(await skipOccurrence(db,p,c));await oracle(p,h.planId);
  }pass('Injected completion, accepted-sequence and durable-outcome failures roll back every effect; same-request retry succeeds');
  {
    const p=await account(),h=await create(p),c=await skip(p,h.planId),before=await snapshot(p);
    for(const client of [reader,db]){await assert.rejects(client.$executeRawUnsafe('DELETE FROM "Trainer2OccurrenceSkip"'));await assert.rejects(client.$executeRawUnsafe('TRUNCATE "Trainer2OccurrenceSkip"'));await assert.rejects(client.$executeRawUnsafe('UPDATE "Trainer2OccurrenceSkip" SET "skippedAt"=now()'));}
    await assert.rejects(reader.trainer2OccurrenceSkip.create({data:{accountId:p.accountId,planId:h.planId,revisionId:h.revisionId,occurrenceId:c.target.occurrenceId,actionId:c.actionId,expected:c.expected,planCompleted:false,priorPlanLifecycle:'Active',endpoint:{}}}));
    for(const mode of ['missing outcome','fake acceptance','wrong binding','wrong account'])await assert.rejects(db.$transaction(async tx=>{
      await tx.$queryRaw`SELECT "accountId" FROM "Trainer2AccountTrainingState" WHERE "accountId"=${p.accountId} FOR UPDATE`;
      await tx.trainer2DurableAction.create({data:{accountId:p.accountId,actionId:c.actionId,...commandBinding(c)}});
      if(mode==='fake acceptance'){await tx.trainer2AccountTrainingState.update({where:{accountId:p.accountId},data:{acceptedSequence:{increment:1}}});await tx.trainer2ActionOutcome.create({data:{accountId:p.accountId,actionId:c.actionId,status:'Accepted',outcome:{status:'Accepted',actionId:c.actionId,commandType:'SkipOccurrence',acceptedSequence:String(BigInt(c.expected.acceptedSequence)+BigInt(1)),result:{planId:h.planId,revisionId:h.revisionId,occurrenceId:c.target.occurrenceId,planCompleted:false}}}});return;}
      await tx.trainer2OccurrenceSkip.create({data:{accountId:mode==='wrong account'?randomUUID():p.accountId,planId:h.planId,revisionId:h.revisionId,occurrenceId:c.target.occurrenceId,actionId:c.actionId,expected:mode==='wrong binding'?{}:c.expected,planCompleted:false,priorPlanLifecycle:'Active',endpoint:{kind:h.intent.endpoint,occurrenceIds:h.intent.occurrences.map(o=>o.id)}}});
    }));assert.deepEqual(await snapshot(p),before);
    const acl=(await admin.query(`SELECT relrowsecurity,relacl::text FROM pg_class WHERE relname='Trainer2OccurrenceSkip'`)).rows[0];assert(acl.relrowsecurity);assert(!/(^|[,{])=/.test(acl.relacl));evidence.push({permissions:acl});
  }pass('Restricted reader/runtime deny direct mutation, missing outcome, forged acceptance and foreign bindings; RLS enabled and no PUBLIC grant');
  // Real browser journeys are kept separate from the SQL oracle and fixtures.
  let base=await startWeb();const browser=await chromium.launch({channel:'msedge',headless:true});
  try{const context=await browser.newContext({viewport:{width:1280,height:900}});await context.routeWebSocket(/.*/,ws=>ws.close());const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(base+'/trainer2/dev/drafts');assert.equal(await page.locator('[data-nextjs-dialog]').count(),0);await page.getByRole('button',{name:'Save plan',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Saved');await page.getByRole('button',{name:'Review plan',exact:true}).click();await page.getByRole('button',{name:'Activate plan',exact:true}).click();await expect(page.getByRole('status').first()).toHaveText('Plan active');
    const planId=new URL(page.url()).searchParams.get('planId')!,planPath=new URL(page.url()).pathname+new URL(page.url()).search;const order=(await readDraft(reader,browserPrincipal,planId))!.intent.occurrences.map(o=>o.id);
    const beforeCancel=await snapshot(browserPrincipal);await page.getByRole('button',{name:'Skip workout',exact:true}).click();await expect(page.getByRole('button',{name:'Start workout',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Skip workout',exact:true})).toBeFocused();assert.deepEqual(await snapshot(browserPrincipal),beforeCancel);
    await page.getByRole('button',{name:'Skip workout',exact:true}).click();await page.screenshot({path:resolve('artifacts/trainer2/skip-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve('artifacts/trainer2/skip-mobile.png'),fullPage:true});await page.getByRole('group',{name:'Confirm skip'}).screenshot({path:resolve('artifacts/trainer2/skip-mobile-confirm.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.getByRole('button',{name:'Confirm skip',exact:true}).evaluate(el=>el.getBoundingClientRect().height>=44));
    let body='';await page.route('**/api/trainer2/occurrences/skip',async route=>{body=route.request().postData()!;assert.equal((await route.fetch()).status(),200);await route.abort();});await page.getByRole('button',{name:'Confirm skip',exact:true}).click();await expect(page.getByRole('button',{name:'Check skip again',exact:true})).toBeEnabled();await page.unroute('**/api/trainer2/occurrences/skip');await page.reload();let retry='';page.on('request',r=>{if(r.url().endsWith('/occurrences/skip'))retry=r.postData()!;});await page.getByRole('button',{name:'Check skip again',exact:true}).click();await expect(page.getByText('Workout marked skipped.',{exact:true})).toBeVisible();assert.equal(retry,body);assert.equal(await oracle(browserPrincipal,planId),order[1]);
    await page.getByRole('button',{name:'Start workout',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout in progress',exact:true})).toBeVisible();await page.getByRole('button',{name:'Enter actual result'}).first().click();await page.getByLabel('Set 1 Actual reps',{exact:true}).first().fill('8');await page.getByRole('button',{name:'Record set',exact:true}).click();await expect(page.getByText(/Saved v1:/)).toBeVisible();await page.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('button',{name:'Finish with unrecorded sets',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout finished',exact:true})).toBeVisible();assert.equal(await oracle(browserPrincipal,planId),order[2]);
    await page.getByRole('button',{name:'Start workout',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout in progress',exact:true})).toBeVisible();const discardedPath=new URL(page.url()).pathname;await page.getByRole('button',{name:'Discard empty workout',exact:true}).click();await page.getByRole('button',{name:'Confirm discard',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout attempt discarded',exact:true})).toBeVisible();await page.getByRole('button',{name:'Skip workout',exact:true}).click();await page.getByRole('button',{name:'Confirm skip',exact:true}).click();await expect(page.getByText('Workout marked skipped.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Workout attempt discarded',exact:true})).toBeVisible();assert.equal(await oracle(browserPrincipal,planId),order[3]);
    for(;;){const n=await next(browserPrincipal,planId);if(!n.occurrence)break;ok(await skipOccurrence(db,browserPrincipal,await skip(browserPrincipal,planId)));}
    const small=await create(browserPrincipal,2);await page.goto(base+`/trainer2/dev/drafts?planId=${small.planId}`);await page.getByRole('button',{name:'Start workout',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout in progress',exact:true})).toBeVisible();await page.getByRole('button',{name:'Enter actual result'}).first().click();await page.getByLabel('Set 1 Actual reps',{exact:true}).fill('8');await page.getByRole('button',{name:'Record set',exact:true}).click();await expect(page.getByText(/Saved v1:/)).toBeVisible();await page.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('button',{name:'Confirm finish',exact:true}).click();await expect(page.getByRole('heading',{name:'Workout finished',exact:true})).toBeVisible();const finishedPath=new URL(page.url()).pathname;
    await page.getByRole('button',{name:'Skip workout',exact:true}).click();await expect(page.getByText(/This is the final workout/)).toBeVisible();await page.getByRole('button',{name:'Confirm skip',exact:true}).click();await expect(page.getByRole('heading',{name:'Plan complete',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Start workout',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Skip workout',exact:true})).toHaveCount(0);await page.getByText('Workout status',{exact:true}).click();await page.screenshot({path:resolve('artifacts/trainer2/skip-completed-mobile.png'),fullPage:true});assert.equal(await oracle(browserPrincipal,small.planId),null);
    const beforeRestart=await snapshot(browserPrincipal);base=await restartWeb();await page.goto(base+finishedPath);await expect(page.getByRole('heading',{name:'Plan complete',exact:true})).toBeVisible();await page.goto(base+discardedPath);await expect(page.getByRole('heading',{name:'Workout attempt discarded',exact:true})).toBeVisible();await page.goto(base+planPath);await expect(page.getByRole('heading',{name:'Plan complete',exact:true})).toBeVisible();assert.deepEqual(await snapshot(browserPrincipal),beforeRestart);assert.deepEqual(errors,[]);evidence.push({browser:'Installed Edge headless; mobile is 390x844 viewport emulation',version:browser.version(),beforeRestart,afterRestart:await snapshot(browserPrincipal)});
    pass('Browser A activate/cancel/skip/lost-response/exact retry/start/record/finish; B start/discard/skip/reload; C mixed completion ending with final skip; bookmarks and same-DB app restart');
  }finally{await browser.close();}
  return {results,evidence,upgrade};
}
