export type ExerciseAliasSeed = { exerciseName: string; alias: string };

export const exerciseAliases: ExerciseAliasSeed[] = [
  { exerciseName: "Barbell Hip Thrust", alias: "Hip Thrust" },
  { exerciseName: "Lying Leg Curl", alias: "Leg Curl" },
  { exerciseName: "Incline Barbell Bench Press", alias: "Incline Barbell Bench" },
  { exerciseName: "Incline Machine Press", alias: "Smith Machine Incline Press" },
  { exerciseName: "Incline Dumbbell Bench Press", alias: "Dumbbell Incline Press" },
  { exerciseName: "Pec Deck Machine", alias: "Pec Deck" },
  { exerciseName: "Barbell Overhead Press", alias: "Overhead Press" },
  { exerciseName: "Dumbbell Overhead Press", alias: "Dumbbell Shoulder Press" },
  { exerciseName: "Dumbbell Lateral Raise", alias: "Lateral Raise" },
  { exerciseName: "Dumbbell Lateral Raise", alias: "Dumbbell Lateral Raises" },
  { exerciseName: "Cable Triceps Pushdown", alias: "Triceps Pushdown" },
  { exerciseName: "Lying Triceps Extension (Skull Crusher)", alias: "Skull Crusher" },
  { exerciseName: "Dip (Chest Emphasis)", alias: "Dips" },
  { exerciseName: "Overhead Dumbbell Extension", alias: "Overhead Triceps Extension" },
  { exerciseName: "Chest-Supported Dumbbell Row", alias: "Chest-Supported Row" },
  { exerciseName: "One-Arm Dumbbell Row", alias: "Single-Arm Dumbbell Row" },
  { exerciseName: "Reverse Pec Deck", alias: "Machine Rear Delt Fly" },
  { exerciseName: "Dumbbell Rear Delt Fly", alias: "Reverse Fly" },
  { exerciseName: "Preacher Curl", alias: "Cable Preacher Curl" },
  { exerciseName: "Farmer's Walk", alias: "Farmer's Carry" },
  { exerciseName: "Dumbbell Overhead Press", alias: "DB Shoulder Press" },
  { exerciseName: "Romanian Deadlift", alias: "Romanian Deadlift (BB)" },
  { exerciseName: "Romanian Deadlift", alias: "DB Romanian Deadlift" },
  { exerciseName: "Incline Dumbbell Bench Press", alias: "Incline DB Press" },
  { exerciseName: "One-Arm Dumbbell Row", alias: "One-Arm DB Row" },
  { exerciseName: "Incline Dumbbell Curl", alias: "Incline DB Curls" },
  { exerciseName: "Lying Triceps Extension (Skull Crusher)", alias: "DB Skull Crushers" },
  { exerciseName: "Dumbbell Lateral Raise", alias: "DB Lateral Raise" },
  { exerciseName: "Face Pull", alias: "Face Pulls (Rope)" },
  { exerciseName: "Cable Triceps Pushdown", alias: "Tricep Rope Pushdown" },
  { exerciseName: "Barbell Bench Press", alias: "Flat Barbell Bench Press" },
  { exerciseName: "Barbell Bench Press", alias: "Decline Barbell Bench" },
  { exerciseName: "Dumbbell Bench Press", alias: "Flat DB Press" },
  { exerciseName: "Bulgarian Split Squat", alias: "Front-Foot Elevated Split Squat" },
  { exerciseName: "Machine Hip Thrust", alias: "Machine Hip Thrust / Glute Drive" },
  { exerciseName: "Machine Hip Thrust", alias: "Glute Drive" },
  { exerciseName: "Machine Hip Thrust", alias: "Glute Trainer" },
  { exerciseName: "Machine Hip Thrust", alias: "Bridge Glute Lifts" },
  { exerciseName: "Iso-Lateral Front Lat Pulldown", alias: "Iso-Lateral Front Pulldown" },
  { exerciseName: "Iso-Lateral Front Lat Pulldown", alias: "Front Lat Pulldown" },
  { exerciseName: "45-Degree Back Extension, Hamstring Bias", alias: "Hamstring-Focused Back Extension" },
  { exerciseName: "45-Degree Back Extension, Hamstring Bias", alias: "Hamstring Bias Back Extension" },
  { exerciseName: "Seated Machine Shrug", alias: "Standing Machine Shrug" },
  { exerciseName: "Seated Machine Shrug", alias: "Machine Shrug" },
  { exerciseName: "Seated Machine Shrug", alias: "Seated Shrug" },
  { exerciseName: "Seated Machine Shrug", alias: "Standing Shrug" },
  { exerciseName: "Seated Dip Machine", alias: "Seated Dip" },
  { exerciseName: "Seated Dip Machine", alias: "Dip Machine" },
  { exerciseName: "Seated Dip Machine", alias: "Machine Dip" },
  { exerciseName: "Oblique Crunch Machine", alias: "Oblique Crunch" },
  { exerciseName: "Torso Rotation Machine", alias: "Torso Rotation" },
  { exerciseName: "Torso Rotation Machine", alias: "Rotary Torso" },
  { exerciseName: "Torso Rotation Machine", alias: "Rotary Torso Machine" },
];
