import type { Constraints, Exercise, Goals, UserProfile, WorkoutHistoryEntry } from "./types";

export const exampleUser: UserProfile = {
  id: "demo-user",
  trainingAge: "intermediate",
  injuries: [],
  age: 30,
  heightCm: 180,
  weightKg: 82,
};

export const exampleGoals: Goals = {
  primary: "hypertrophy",
  secondary: "conditioning",
};

export const exampleConstraints: Constraints = {
  daysPerWeek: 4,
  sessionMinutes: 55,
  splitType: "upper_lower",
};

export const exampleExerciseLibrary: Exercise[] = [
  {
    id: "bench",
    name: "Barbell Bench Press",
    movementPatterns: ["horizontal_push"],
    splitTags: ["push"],
    jointStress: "high",
    isMainLiftEligible: true,
    fatigueCost: 4,
    sfrScore: 2,
    lengthPositionScore: 3,
    equipment: ["barbell", "bench", "rack"],
    primaryMuscles: ["Chest", "Triceps"],
    secondaryMuscles: ["Front Delts"],
    contraindications: { shoulder: true },
  },
  {
    id: "row",
    name: "Barbell Row",
    movementPatterns: ["horizontal_pull"],
    splitTags: ["pull"],
    jointStress: "medium",
    isMainLiftEligible: true,
    fatigueCost: 4,
    sfrScore: 2,
    lengthPositionScore: 3,
    equipment: ["barbell"],
    primaryMuscles: ["Lats", "Upper Back"],
    secondaryMuscles: ["Biceps", "Rear Delts", "Forearms"],
  },
  {
    id: "squat",
    name: "Barbell Back Squat",
    movementPatterns: ["squat"],
    splitTags: ["legs"],
    jointStress: "high",
    isMainLiftEligible: true,
    fatigueCost: 5,
    sfrScore: 1,
    lengthPositionScore: 3,
    equipment: ["barbell", "rack"],
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Lower Back"],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    movementPatterns: ["hinge"],
    splitTags: ["legs"],
    jointStress: "medium",
    isMainLiftEligible: true,
    fatigueCost: 3,
    sfrScore: 2,
    lengthPositionScore: 4,
    equipment: ["barbell"],
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back", "Core"],
  },
  {
    id: "lat-pull",
    name: "Lat Pulldown",
    movementPatterns: ["vertical_pull"],
    splitTags: ["pull"],
    jointStress: "medium",
    fatigueCost: 3,
    sfrScore: 4,
    lengthPositionScore: 3,
    equipment: ["cable", "machine"],
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Forearms"],
  },
  {
    id: "db-press",
    name: "Dumbbell Bench Press",
    movementPatterns: ["horizontal_push"],
    splitTags: ["push"],
    jointStress: "medium",
    fatigueCost: 3,
    sfrScore: 3,
    lengthPositionScore: 4,
    equipment: ["dumbbell", "bench"],
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
  },
  {
    id: "split-squat",
    name: "Bulgarian Split Squat",
    movementPatterns: ["lunge"],
    splitTags: ["legs"],
    jointStress: "high",
    fatigueCost: 3,
    sfrScore: 3,
    lengthPositionScore: 4,
    equipment: ["dumbbell", "bench"],
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    movementPatterns: ["squat"],
    splitTags: ["legs"],
    jointStress: "medium",
    fatigueCost: 3,
    sfrScore: 4,
    lengthPositionScore: 2,
    equipment: ["machine"],
    primaryMuscles: ["Quads"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    movementPatterns: ["horizontal_pull"],
    splitTags: ["pull"],
    jointStress: "low",
    fatigueCost: 2,
    sfrScore: 4,
    lengthPositionScore: 3,
    equipment: ["cable"],
    primaryMuscles: ["Rear Delts", "Upper Back"],
    secondaryMuscles: ["Side Delts"],
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    movementPatterns: ["vertical_push"],
    splitTags: ["push"],
    jointStress: "low",
    fatigueCost: 2,
    sfrScore: 4,
    lengthPositionScore: 3,
    equipment: ["dumbbell"],
    primaryMuscles: ["Side Delts"],
  },
  {
    id: "plank",
    name: "Plank",
    movementPatterns: ["anti_rotation"],
    splitTags: ["core"],
    jointStress: "low",
    fatigueCost: 1,
    sfrScore: 3,
    lengthPositionScore: 1,
    equipment: ["bodyweight"],
    primaryMuscles: ["Core"],
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    movementPatterns: ["carry"],
    splitTags: ["conditioning"],
    jointStress: "medium",
    fatigueCost: 2,
    sfrScore: 3,
    lengthPositionScore: 1,
    equipment: ["dumbbell"],
    primaryMuscles: ["Forearms", "Core"],
    secondaryMuscles: ["Upper Back"],
  },
];

export const exampleHistory: WorkoutHistoryEntry[] = [
  {
    date: new Date(Date.now() - 86400000).toISOString(),
    completed: true,
    readinessScore: 3,
    exercises: [
      {
        exerciseId: "bench",
        primaryMuscles: ["Chest", "Triceps"],
        sets: [
          { exerciseId: "bench", setIndex: 1, reps: 8, rpe: 7, load: 175 },
          { exerciseId: "bench", setIndex: 2, reps: 8, rpe: 7, load: 175 },
          { exerciseId: "bench", setIndex: 3, reps: 8, rpe: 7.5, load: 175 },
        ],
      },
    ],
  },
];
