import type { V2PlannerSlotId, V2PlannerSlotDefinition, V2TargetSkeleton } from "./types";

export const V2_TARGET_SLOT_SEQUENCE: V2PlannerSlotId[] = [
  "upper_a",
  "lower_a",
  "upper_b",
  "lower_b",
];

export const V2_TARGET_SLOT_SKELETON: V2PlannerSlotDefinition[] = [
  {
    slotId: "upper_a",
    intent: "horizontal push/pull + rear/side delt/triceps support",
    targetSessionSets: { min: 17, max: 24 },
    lanes: [
      {
        laneId: "chest_anchor",
        required: true,
        role: "anchor",
        primaryMuscles: ["Chest"],
        preferredExerciseClasses: ["horizontal_press", "slight_incline_press"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "row_anchor",
        required: true,
        role: "anchor",
        primaryMuscles: ["Upper Back", "Lats"],
        preferredExerciseClasses: ["chest_supported_row", "cable_row", "t_bar_row"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "vertical_pull_support",
        targetLaneId: "vertical_pull",
        required: true,
        role: "support",
        primaryMuscles: ["Lats"],
        preferredExerciseClasses: ["vertical_pull"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "chest_secondary",
        required: true,
        role: "support",
        primaryMuscles: ["Chest"],
        preferredExerciseClasses: ["fly", "machine_press", "cable_press"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "rear_delt",
        required: true,
        role: "accessory",
        primaryMuscles: ["Rear Delts"],
        preferredExerciseClasses: ["rear_delt_isolation"],
        targetSets: { min: 4, preferred: 4, max: 4 },
      },
      {
        laneId: "side_delt_isolation",
        targetLaneId: "side_delt_support",
        required: true,
        role: "accessory",
        primaryMuscles: ["Side Delts"],
        preferredExerciseClasses: ["lateral_raise", "low_collateral_side_delt"],
        targetSets: { min: 4, preferred: 4, max: 4 },
      },
      {
        laneId: "triceps",
        required: true,
        role: "accessory",
        primaryMuscles: ["Triceps"],
        preferredExerciseClasses: ["triceps_isolation", "pressdown"],
        targetSets: { min: 4, preferred: 4, max: 4 },
      },
    ],
  },
  {
    slotId: "lower_a",
    intent: "squat-dominant + hamstring support",
    targetSessionSets: { min: 12, max: 18 },
    lanes: [
      {
        laneId: "squat_anchor",
        required: true,
        role: "anchor",
        primaryMuscles: ["Quads"],
        preferredExerciseClasses: ["squat_pattern"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "quad_isolation",
        required: true,
        role: "support",
        primaryMuscles: ["Quads"],
        preferredExerciseClasses: ["leg_extension"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "hamstring_curl",
        targetLaneId: "knee_flexion_curl",
        required: true,
        role: "support",
        primaryMuscles: ["Hamstrings"],
        preferredExerciseClasses: ["knee_flexion_curl"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "secondary_hinge",
        targetLaneId: "hinge_anchor",
        required: false,
        role: "optional",
        primaryMuscles: ["Hamstrings"],
        preferredExerciseClasses: ["low_dose_hinge"],
        targetSets: { min: 0, preferred: 0, max: 2 },
      },
      {
        laneId: "calves",
        required: true,
        role: "accessory",
        primaryMuscles: ["Calves"],
        preferredExerciseClasses: ["calf_isolation"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
    ],
  },
  {
    slotId: "upper_b",
    intent: "vertical push/pull + side delts/arms + second chest exposure",
    targetSessionSets: { min: 15, max: 21 },
    lanes: [
      {
        laneId: "vertical_press",
        targetLaneId: "vertical_press_support",
        required: true,
        role: "support",
        primaryMuscles: ["Front Delts"],
        preferredExerciseClasses: ["vertical_press"],
        targetSets: { min: 2, preferred: 2, max: 2 },
      },
      {
        laneId: "vertical_pull_anchor",
        targetLaneId: "vertical_pull",
        required: true,
        role: "anchor",
        primaryMuscles: ["Lats"],
        preferredExerciseClasses: ["vertical_pull"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "chest_second_exposure",
        targetLaneId: "chest_secondary",
        required: true,
        role: "support",
        primaryMuscles: ["Chest"],
        preferredExerciseClasses: ["distinct_chest_press_or_fly"],
        targetSets: { min: 3, preferred: 3, max: 3 },
      },
      {
        laneId: "row_support",
        targetLaneId: "row_anchor",
        required: true,
        role: "support",
        primaryMuscles: ["Upper Back", "Lats"],
        preferredExerciseClasses: ["horizontal_pull_support"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "side_delt_isolation",
        required: true,
        role: "accessory",
        primaryMuscles: ["Side Delts"],
        preferredExerciseClasses: ["lateral_raise", "low_collateral_side_delt"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "biceps",
        required: true,
        role: "accessory",
        primaryMuscles: ["Biceps"],
        preferredExerciseClasses: ["biceps_isolation"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "optional_triceps_if_under_target",
        targetLaneId: "triceps",
        required: false,
        role: "optional",
        primaryMuscles: ["Triceps"],
        preferredExerciseClasses: ["triceps_isolation"],
        targetSets: { min: 1, preferred: 1, max: 2 },
      },
    ],
  },
  {
    slotId: "lower_b",
    intent: "hinge-dominant + quad support + calves",
    targetSessionSets: { min: 10, max: 16 },
    lanes: [
      {
        laneId: "hinge_anchor",
        required: true,
        role: "anchor",
        primaryMuscles: ["Hamstrings", "Glutes"],
        preferredExerciseClasses: [
          "hinge_compound",
          "low_axial_hip_extension_anchor",
        ],
        targetSets: { min: 3, preferred: 3, max: 3 },
      },
      {
        laneId: "knee_flexion_curl",
        required: true,
        role: "support",
        primaryMuscles: ["Hamstrings"],
        preferredExerciseClasses: ["hamstring_curl"],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "quad_support",
        required: true,
        role: "support",
        primaryMuscles: ["Quads"],
        preferredExerciseClasses: [
          "leg_press",
          "squat_pattern",
          "quad_isolation",
          "lunge",
        ],
        targetSets: { min: 2, preferred: 3, max: 3 },
      },
      {
        laneId: "calves",
        required: true,
        role: "accessory",
        primaryMuscles: ["Calves"],
        preferredExerciseClasses: ["calf_isolation"],
        targetSets: { min: 3, preferred: 4, max: 4 },
      },
      {
        laneId: "optional_glute_core_if_recoverable",
        targetLaneId: "optional_core_adductor_glute",
        required: false,
        role: "optional",
        primaryMuscles: ["Glutes", "Core"],
        preferredExerciseClasses: ["glute_or_core_accessory"],
        targetSets: { min: 0, preferred: 1, max: 2 },
      },
    ],
  },
];

export function buildV2TargetSkeleton(): V2TargetSkeleton {
  return {
    split: "upper_lower_4x",
    weeks: 5,
    slotSequence: [...V2_TARGET_SLOT_SEQUENCE],
    slots: V2_TARGET_SLOT_SKELETON.map((slot) => ({
      ...slot,
      targetSessionSets: { ...slot.targetSessionSets },
      lanes: slot.lanes.map((lane) => ({
        ...lane,
        primaryMuscles: [...lane.primaryMuscles],
        preferredExerciseClasses: [...lane.preferredExerciseClasses],
        targetSets: { ...lane.targetSets },
      })),
    })),
  };
}
