export const EXPECTED_CATALOG_IDENTITY_KEYS_V1 = [
  ["Barbell Back Squat", "barbell-back-squat"],
  ["Front Squat", "front-squat"],
  ["Goblet Squat", "goblet-squat"],
  ["Hack Squat", "hack-squat"],
  ["Leg Press", "leg-press"],
  ["Belt Squat", "belt-squat"],
  ["Bulgarian Split Squat", "bulgarian-split-squat"],
  ["Walking Lunge", "walking-lunge"],
  ["Dumbbell Reverse Lunge", "dumbbell-reverse-lunge"],
  ["Reverse Lunge", "reverse-lunge"],
  ["Leg Extension", "leg-extension"],
  ["Sissy Squat", "sissy-squat"],
  ["Conventional Deadlift", "conventional-deadlift"],
  ["Sumo Deadlift", "sumo-deadlift"],
  ["Trap Bar Deadlift", "trap-bar-deadlift"],
  ["Barbell Romanian Deadlift", "barbell-romanian-deadlift"],
  ["Dumbbell Romanian Deadlift", "dumbbell-romanian-deadlift"],
  ["Romanian Deadlift", "romanian-deadlift"],
  ["Stiff-Legged Deadlift", "stiff-legged-deadlift"],
  ["Good Morning", "good-morning"],
  ["Lying Leg Curl", "lying-leg-curl"],
  ["Seated Leg Curl", "seated-leg-curl"],
  ["Nordic Hamstring Curl", "nordic-hamstring-curl"],
  ["Barbell Hip Thrust", "barbell-hip-thrust"],
  ["Machine Hip Thrust", "machine-hip-thrust"],
  ["Single-Leg Hip Thrust", "single-leg-hip-thrust"],
  ["Glute Bridge", "glute-bridge"],
  ["Back Extension (45 Degree)", "back-extension-45-degree"],
  ["45-Degree Back Extension, Hamstring Bias", "45-degree-back-extension-hamstring-bias"],
  ["Reverse Hyperextension", "reverse-hyperextension"],
  ["Cable Pull-Through", "cable-pull-through"],
  ["Hip Abduction Machine", "hip-abduction-machine"],
  ["Cable Hip Abduction", "cable-hip-abduction"],
  ["Hip Adduction Machine", "hip-adduction-machine"],
  ["Copenhagen Plank", "copenhagen-plank"],
  ["Selectorized Standing Calf Raise", "selectorized-standing-calf-raise"],
  ["Standing Calf Raise", "standing-calf-raise"],
  ["Seated Calf Raise", "seated-calf-raise"],
  ["Leg Press Calf Raise", "leg-press-calf-raise"],
  ["Barbell Bench Press", "barbell-bench-press"],
  ["Incline Barbell Bench Press", "incline-barbell-bench-press"],
  ["Decline Barbell Bench Press", "decline-barbell-bench-press"],
  ["Dumbbell Bench Press", "dumbbell-bench-press"],
  ["Incline Dumbbell Bench Press", "incline-dumbbell-bench-press"],
  ["Decline Dumbbell Bench Press", "decline-dumbbell-bench-press"],
  ["Machine Chest Press", "machine-chest-press"],
  ["Incline Machine Press", "incline-machine-press"],
  ["Iso-Lateral Incline Press", "iso-lateral-incline-press"],
  ["Iso-Lateral Decline Press", "iso-lateral-decline-press"],
  ["Dumbbell Fly", "dumbbell-fly"],
  ["Incline Dumbbell Fly", "incline-dumbbell-fly"],
  ["Cable Fly", "cable-fly"],
  ["Low-to-High Cable Fly", "low-to-high-cable-fly"],
  ["Pec Deck Machine", "pec-deck-machine"],
  ["Push-Up", "push-up"],
  ["Deficit Push-Up", "deficit-push-up"],
  ["Dip (Chest Emphasis)", "dip-chest-emphasis"],
  ["Barbell Overhead Press", "barbell-overhead-press"],
  ["Seated Barbell Overhead Press", "seated-barbell-overhead-press"],
  ["Dumbbell Overhead Press", "dumbbell-overhead-press"],
  ["Arnold Press", "arnold-press"],
  ["Machine Shoulder Press", "machine-shoulder-press"],
  ["Landmine Press", "landmine-press"],
  ["Dumbbell Lateral Raise", "dumbbell-lateral-raise"],
  ["Cable Lateral Raise", "cable-lateral-raise"],
  ["Machine Lateral Raise", "machine-lateral-raise"],
  ["Dumbbell Front Raise", "dumbbell-front-raise"],
  ["Cable Front Raise", "cable-front-raise"],
  ["Dumbbell Rear Delt Fly", "dumbbell-rear-delt-fly"],
  ["Cable Rear Delt Fly", "cable-rear-delt-fly"],
  ["Reverse Pec Deck", "reverse-pec-deck"],
  ["Face Pull", "face-pull"],
  ["Close-Grip Bench Press", "close-grip-bench-press"],
  ["Dip (Triceps Emphasis)", "dip-triceps-emphasis"],
  ["Seated Dip Machine", "seated-dip-machine"],
  ["Overhead Cable Triceps Extension", "overhead-cable-triceps-extension"],
  ["Overhead Dumbbell Extension", "overhead-dumbbell-extension"],
  ["Lying Triceps Extension (Skull Crusher)", "lying-triceps-extension-skull-crusher"],
  ["Cable Triceps Pushdown", "cable-triceps-pushdown"],
  ["Rope Triceps Pushdown", "rope-triceps-pushdown"],
  ["Diamond Push-Up", "diamond-push-up"],
  ["Pull-Up", "pull-up"],
  ["Chin-Up", "chin-up"],
  ["Weighted Pull-Up", "weighted-pull-up"],
  ["Machine-Assisted Pull-Up", "machine-assisted-pull-up"],
  ["Lat Pulldown", "lat-pulldown"],
  ["Iso-Lateral Front Lat Pulldown", "iso-lateral-front-lat-pulldown"],
  ["Close-Grip Lat Pulldown", "close-grip-lat-pulldown"],
  ["Straight-Arm Pulldown", "straight-arm-pulldown"],
  ["Dumbbell Pullover", "dumbbell-pullover"],
  ["Cable Pullover", "cable-pullover"],
  ["Barbell Row", "barbell-row"],
  ["Pendlay Row", "pendlay-row"],
  ["T-Bar Row", "t-bar-row"],
  ["Chest-Supported T-Bar Row", "chest-supported-t-bar-row"],
  ["One-Arm Dumbbell Row", "one-arm-dumbbell-row"],
  ["Dumbbell Row", "dumbbell-row"],
  ["Chest-Supported Dumbbell Row", "chest-supported-dumbbell-row"],
  ["Seated Cable Row", "seated-cable-row"],
  ["Close-Grip Seated Cable Row", "close-grip-seated-cable-row"],
  ["Iso-Lateral High Row", "iso-lateral-high-row"],
  ["Iso-Lateral Low Row", "iso-lateral-low-row"],
  ["Meadows Row", "meadows-row"],
  ["Inverted Row", "inverted-row"],
  ["Barbell Shrug", "barbell-shrug"],
  ["Dumbbell Shrug", "dumbbell-shrug"],
  ["Seated Machine Shrug", "seated-machine-shrug"],
  ["Barbell Curl", "barbell-curl"],
  ["EZ-Bar Curl", "ez-bar-curl"],
  ["Dumbbell Curl", "dumbbell-curl"],
  ["Alternating Dumbbell Curl", "alternating-dumbbell-curl"],
  ["Incline Dumbbell Curl", "incline-dumbbell-curl"],
  ["Hammer Curl", "hammer-curl"],
  ["Cross-Body Hammer Curl", "cross-body-hammer-curl"],
  ["Cable Curl", "cable-curl"],
  ["Bayesian Curl", "bayesian-curl"],
  ["Preacher Curl", "preacher-curl"],
  ["Spider Curl", "spider-curl"],
  ["Concentration Curl", "concentration-curl"],
  ["Reverse Curl", "reverse-curl"],
  ["Wrist Curl", "wrist-curl"],
  ["Reverse Wrist Curl", "reverse-wrist-curl"],
  ["Farmer's Walk", "farmers-walk"],
  ["Dead Hang", "dead-hang"],
  ["Plank", "plank"],
  ["RKC Plank", "rkc-plank"],
  ["Side Plank", "side-plank"],
  ["Ab Wheel Rollout", "ab-wheel-rollout"],
  ["Pallof Press", "pallof-press"],
  ["Cable Pallof Press", "cable-pallof-press"],
  ["Cable Crunch", "cable-crunch"],
  ["Machine Crunch", "machine-crunch"],
  ["Oblique Crunch Machine", "oblique-crunch-machine"],
  ["Hanging Leg Raise", "hanging-leg-raise"],
  ["Hanging Knee Raise", "hanging-knee-raise"],
  ["Dragon Flag", "dragon-flag"],
  ["Decline Sit-Up", "decline-sit-up"],
  ["Reverse Crunch", "reverse-crunch"],
  ["Bicycle Crunch", "bicycle-crunch"],
  ["Russian Twist", "russian-twist"],
  ["Torso Rotation Machine", "torso-rotation-machine"],
  ["Wood Chop", "wood-chop"],
  ["Landmine Rotation", "landmine-rotation"],
  ["Suitcase Carry", "suitcase-carry"],
  ["Overhead Carry", "overhead-carry"],
  ["Sled Push", "sled-push"],
  ["Sled Pull", "sled-pull"],
  ["Sled Drag", "sled-drag"],
  ["Cable Crossover", "cable-crossover"],
  ["Neutral Grip Pull-Up", "neutral-grip-pull-up"],
] as const;

export const EXPECTED_CATALOG_KEY_MEMBERSHIP_V1 =
  EXPECTED_CATALOG_IDENTITY_KEYS_V1.map(([, catalogKey]) => catalogKey);
