export type ReviewedStep2AMeasurementCategory =
  | "COMPLETE_SUPPORTED"
  | "AMBIGUOUS_EXECUTION_IDENTITY"
  | "UNSUPPORTED_MEASUREMENT_SEMANTICS";

// Independent regression oracle for the reviewed Step 2A identity partition.
// Production measurement behavior remains owned by catalog-support-manifest.ts.
export const REVIEWED_STEP_2A_MEASUREMENT_MEMBERSHIP = [
  ["Barbell Back Squat", "COMPLETE_SUPPORTED"],
  ["Front Squat", "COMPLETE_SUPPORTED"],
  ["Goblet Squat", "COMPLETE_SUPPORTED"],
  ["Hack Squat", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Leg Press", "COMPLETE_SUPPORTED"],
  ["Belt Squat", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Bulgarian Split Squat", "COMPLETE_SUPPORTED"],
  ["Walking Lunge", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Dumbbell Reverse Lunge", "COMPLETE_SUPPORTED"],
  ["Reverse Lunge", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Leg Extension", "COMPLETE_SUPPORTED"],
  ["Sissy Squat", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Conventional Deadlift", "COMPLETE_SUPPORTED"],
  ["Sumo Deadlift", "COMPLETE_SUPPORTED"],
  ["Trap Bar Deadlift", "COMPLETE_SUPPORTED"],
  ["Barbell Romanian Deadlift", "COMPLETE_SUPPORTED"],
  ["Dumbbell Romanian Deadlift", "COMPLETE_SUPPORTED"],
  ["Romanian Deadlift", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Stiff-Legged Deadlift", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Good Morning", "COMPLETE_SUPPORTED"],
  ["Lying Leg Curl", "COMPLETE_SUPPORTED"],
  ["Seated Leg Curl", "COMPLETE_SUPPORTED"],
  ["Nordic Hamstring Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Barbell Hip Thrust", "COMPLETE_SUPPORTED"],
  ["Machine Hip Thrust", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Single-Leg Hip Thrust", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Glute Bridge", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Back Extension (45 Degree)", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["45-Degree Back Extension, Hamstring Bias", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Reverse Hyperextension", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Cable Pull-Through", "COMPLETE_SUPPORTED"],
  ["Hip Abduction Machine", "COMPLETE_SUPPORTED"],
  ["Cable Hip Abduction", "COMPLETE_SUPPORTED"],
  ["Hip Adduction Machine", "COMPLETE_SUPPORTED"],
  ["Copenhagen Plank", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Selectorized Standing Calf Raise", "COMPLETE_SUPPORTED"],
  ["Standing Calf Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Seated Calf Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Leg Press Calf Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Barbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Incline Barbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Decline Barbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Dumbbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Incline Dumbbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Decline Dumbbell Bench Press", "COMPLETE_SUPPORTED"],
  ["Machine Chest Press", "COMPLETE_SUPPORTED"],
  ["Incline Machine Press", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Iso-Lateral Incline Press", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Iso-Lateral Decline Press", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Dumbbell Fly", "COMPLETE_SUPPORTED"],
  ["Incline Dumbbell Fly", "COMPLETE_SUPPORTED"],
  ["Cable Fly", "COMPLETE_SUPPORTED"],
  ["Low-to-High Cable Fly", "COMPLETE_SUPPORTED"],
  ["Pec Deck Machine", "COMPLETE_SUPPORTED"],
  ["Push-Up", "COMPLETE_SUPPORTED"],
  ["Deficit Push-Up", "COMPLETE_SUPPORTED"],
  ["Dip (Chest Emphasis)", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Barbell Overhead Press", "COMPLETE_SUPPORTED"],
  ["Seated Barbell Overhead Press", "COMPLETE_SUPPORTED"],
  ["Dumbbell Overhead Press", "COMPLETE_SUPPORTED"],
  ["Arnold Press", "COMPLETE_SUPPORTED"],
  ["Machine Shoulder Press", "COMPLETE_SUPPORTED"],
  ["Landmine Press", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Dumbbell Lateral Raise", "COMPLETE_SUPPORTED"],
  ["Cable Lateral Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Machine Lateral Raise", "COMPLETE_SUPPORTED"],
  ["Dumbbell Front Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Cable Front Raise", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Dumbbell Rear Delt Fly", "COMPLETE_SUPPORTED"],
  ["Cable Rear Delt Fly", "COMPLETE_SUPPORTED"],
  ["Reverse Pec Deck", "COMPLETE_SUPPORTED"],
  ["Face Pull", "COMPLETE_SUPPORTED"],
  ["Close-Grip Bench Press", "COMPLETE_SUPPORTED"],
  ["Dip (Triceps Emphasis)", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Seated Dip Machine", "COMPLETE_SUPPORTED"],
  ["Overhead Cable Triceps Extension", "COMPLETE_SUPPORTED"],
  ["Overhead Dumbbell Extension", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Lying Triceps Extension (Skull Crusher)", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Cable Triceps Pushdown", "COMPLETE_SUPPORTED"],
  ["Rope Triceps Pushdown", "COMPLETE_SUPPORTED"],
  ["Diamond Push-Up", "COMPLETE_SUPPORTED"],
  ["Pull-Up", "COMPLETE_SUPPORTED"],
  ["Chin-Up", "COMPLETE_SUPPORTED"],
  ["Weighted Pull-Up", "COMPLETE_SUPPORTED"],
  ["Machine-Assisted Pull-Up", "COMPLETE_SUPPORTED"],
  ["Lat Pulldown", "COMPLETE_SUPPORTED"],
  ["Iso-Lateral Front Lat Pulldown", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Close-Grip Lat Pulldown", "COMPLETE_SUPPORTED"],
  ["Straight-Arm Pulldown", "COMPLETE_SUPPORTED"],
  ["Dumbbell Pullover", "COMPLETE_SUPPORTED"],
  ["Cable Pullover", "COMPLETE_SUPPORTED"],
  ["Barbell Row", "COMPLETE_SUPPORTED"],
  ["Pendlay Row", "COMPLETE_SUPPORTED"],
  ["T-Bar Row", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Chest-Supported T-Bar Row", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["One-Arm Dumbbell Row", "COMPLETE_SUPPORTED"],
  ["Dumbbell Row", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Chest-Supported Dumbbell Row", "COMPLETE_SUPPORTED"],
  ["Seated Cable Row", "COMPLETE_SUPPORTED"],
  ["Close-Grip Seated Cable Row", "COMPLETE_SUPPORTED"],
  ["Iso-Lateral High Row", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Iso-Lateral Low Row", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Meadows Row", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Inverted Row", "COMPLETE_SUPPORTED"],
  ["Barbell Shrug", "COMPLETE_SUPPORTED"],
  ["Dumbbell Shrug", "COMPLETE_SUPPORTED"],
  ["Seated Machine Shrug", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Barbell Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["EZ-Bar Curl", "COMPLETE_SUPPORTED"],
  ["Dumbbell Curl", "COMPLETE_SUPPORTED"],
  ["Alternating Dumbbell Curl", "COMPLETE_SUPPORTED"],
  ["Incline Dumbbell Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Hammer Curl", "COMPLETE_SUPPORTED"],
  ["Cross-Body Hammer Curl", "COMPLETE_SUPPORTED"],
  ["Cable Curl", "COMPLETE_SUPPORTED"],
  ["Bayesian Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Preacher Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Spider Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Concentration Curl", "COMPLETE_SUPPORTED"],
  ["Reverse Curl", "COMPLETE_SUPPORTED"],
  ["Wrist Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Reverse Wrist Curl", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Farmer's Walk", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Dead Hang", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Plank", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["RKC Plank", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Side Plank", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Ab Wheel Rollout", "COMPLETE_SUPPORTED"],
  ["Pallof Press", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Cable Crunch", "COMPLETE_SUPPORTED"],
  ["Machine Crunch", "COMPLETE_SUPPORTED"],
  ["Oblique Crunch Machine", "COMPLETE_SUPPORTED"],
  ["Hanging Leg Raise", "COMPLETE_SUPPORTED"],
  ["Hanging Knee Raise", "COMPLETE_SUPPORTED"],
  ["Dragon Flag", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Decline Sit-Up", "COMPLETE_SUPPORTED"],
  ["Reverse Crunch", "COMPLETE_SUPPORTED"],
  ["Bicycle Crunch", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Russian Twist", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Torso Rotation Machine", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Wood Chop", "AMBIGUOUS_EXECUTION_IDENTITY"],
  ["Landmine Rotation", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Suitcase Carry", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Overhead Carry", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Sled Push", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Sled Pull", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Sled Drag", "UNSUPPORTED_MEASUREMENT_SEMANTICS"],
  ["Cable Crossover", "COMPLETE_SUPPORTED"],
  ["Neutral Grip Pull-Up", "COMPLETE_SUPPORTED"],
] as const satisfies readonly (readonly [
  identity: string,
  category: ReviewedStep2AMeasurementCategory,
])[];
